using AdielSystem.Application.Common;
using AdielSystem.Application.Security;
namespace AdielSystem.Application.Expenses;
public sealed class ExpenseService(IExpenseRepository repository, ICurrentUserAccessor user)
{
 public Task<ExpensePageDto> ListAsync(string? search,string? status,bool archived,int page,int pageSize,CancellationToken token)=>page<=0||pageSize is <1 or >100?throw new RequestValidationException("Page must be greater than zero and page size must be between 1 and 100."):repository.ListAsync(search?.Trim()??string.Empty,string.IsNullOrWhiteSpace(status)?null:status.Trim(),archived,page,pageSize,token);
 public async Task<ExpenseDto> GetAsync(Guid id,CancellationToken token)=>await repository.GetAsync(id,token)??throw new ResourceNotFoundException($"Expense '{id}' was not found.");
 public Task<ExpenseDto> CreateAsync(SaveExpenseRequest r,CancellationToken token){Validate(r);return repository.CreateAsync(r,user.GetRequiredUser(),token);} public Task<ExpenseDto> UpdateAsync(Guid id,SaveExpenseRequest r,CancellationToken token){if(r.Version is null or <=0)throw new RequestValidationException("The current expense version is required.");Validate(r);return repository.UpdateAsync(id,r,user.GetRequiredUser(),token);} public Task<ExpenseDto> ChangeStatusAsync(Guid id,ChangeExpenseStatusRequest r,CancellationToken token)=>r.Version<=0?throw new RequestValidationException("The current expense version is required."):repository.ChangeStatusAsync(id,r,user.GetRequiredUser(),token); public Task<ExpenseDto> ArchiveAsync(Guid id,ChangeExpenseArchiveRequest r,CancellationToken token)=>repository.SetArchivedAsync(id,r,true,user.GetRequiredUser(),token); public Task<ExpenseDto> RestoreAsync(Guid id,ChangeExpenseArchiveRequest r,CancellationToken token)=>repository.SetArchivedAsync(id,r,false,user.GetRequiredUser(),token); public Task<ExpenseDto> GenerateFromPurchaseOrderAsync(Guid id,CancellationToken token)=>repository.GenerateFromPurchaseOrderAsync(id,user.GetRequiredUser(),token);
 private static void Validate(SaveExpenseRequest r){if(r.ExpenseDate==default||string.IsNullOrWhiteSpace(r.Payee)||string.IsNullOrWhiteSpace(r.Category)||r.Amount<=0||string.IsNullOrWhiteSpace(r.PaymentMethod)||string.IsNullOrWhiteSpace(r.Status))throw new RequestValidationException("Expense date, payee, category, amount, payment method and status are required.");if(r.Status is not ("Paid" or "Verifying" or "To pay" or "Overdue"))throw new RequestValidationException("Choose a valid active expense status. Use the void action to cancel an expense.");if(!string.IsNullOrWhiteSpace(r.InvoiceUrl)&&(!Uri.TryCreate(r.InvoiceUrl,UriKind.Absolute,out var url)||(url.Scheme!=Uri.UriSchemeHttp&&url.Scheme!=Uri.UriSchemeHttps)))throw new RequestValidationException("Invoice URL must be an absolute HTTP or HTTPS URL.");}
}
