import { apiRequest } from './client'

export type PurchaseOrderDocumentStatus = 'Draft' | 'Sent' | 'Approved' | 'For Revision' | 'Cancelled'
export type PurchaseOrderDeliveryStatus = 'Pending' | 'Partially Delivered' | 'Delivered'
export type PurchaseOrderPaymentStatus = 'Not Due' | 'To Pay' | 'Partially Paid' | 'Overdue' | 'Paid'
export type PurchaseOrderStatus = 'Delivered' | 'For Payment' | 'Waiting for Delivery' | 'Cancelled' | 'Approved' | 'For Revision' | 'Sent' | 'Not yet sent'
export type PurchaseOrderLine = { id: string; itemId: string | null; variantId: string | null; photo: string; itemName: string; variantLabel: string; productCode: string; unitOfMeasure: string; quantity: number; unitCost: number; lineAmount: number }
export type PurchaseOrderCharge = { id: string; label: string; amount: number; position: number }
export type PurchaseOrderPayment = { id: string; paymentDate: string; amount: number; balanceAfter: number; method: string; referenceNumber: string; notes: string; createdAt: string }
export type PurchaseOrder = { id: string; poNumber: string; orderDate: string; clientId: string | null; clientName: string; supplierId: string | null; supplierName: string; contactPerson: string; subject: string; quotationId: string | null; quotationNumber: string; paymentMethod: string; paymentTerm: string; deliveryLocation: string; deliveryMode: string; notes: string; terms: string; subtotalAmount: number; vatEnabled: boolean; vatRate: number; vatAmount: number; totalAmount: number; totalPaid: number; balance: number; status: PurchaseOrderStatus; documentStatus: PurchaseOrderDocumentStatus; deliveryStatus: PurchaseOrderDeliveryStatus; paymentStatus: PurchaseOrderPaymentStatus; voidReason: string | null; lines: PurchaseOrderLine[]; charges: PurchaseOrderCharge[]; payments: PurchaseOrderPayment[]; createdAt: string; updatedAt: string; archivedAt: string | null; version: number }
export type SavePurchaseOrder = { orderDate: string; clientId: string | null; clientName: string; supplierId: string | null; supplierName: string; contactPerson: string; subject: string; quotationId: string | null; paymentMethod: string; paymentTerm: string; deliveryLocation: string; deliveryMode: string; notes: string; terms: string; vatEnabled: boolean; lines: Array<Omit<PurchaseOrderLine, 'id' | 'lineAmount'>>; charges: Array<Pick<PurchaseOrderCharge, 'label' | 'amount'>>; intent: 'draft' | 'send'; version?: number }
export type PurchaseOrderPage = { items: PurchaseOrder[]; page: number; pageSize: number; total: number }
export const listPurchaseOrders = (query: { search?: string; supplierId?: string; status?: PurchaseOrderStatus; archivedOnly?: boolean; page?: number; pageSize?: number } = {}) => { const p = new URLSearchParams(); if (query.search) p.set('search', query.search); if (query.supplierId) p.set('supplierId', query.supplierId); if (query.status) p.set('status', query.status); if (query.archivedOnly) p.set('archivedOnly', 'true'); p.set('page', String(query.page ?? 1)); p.set('pageSize', String(query.pageSize ?? 100)); return apiRequest<PurchaseOrderPage>('/purchase-orders?' + p.toString()) }
export const createPurchaseOrder = (value: SavePurchaseOrder) => apiRequest<PurchaseOrder>('/purchase-orders', { method: 'POST', body: JSON.stringify(value) })
export const updatePurchaseOrder = (id: string, value: SavePurchaseOrder) => apiRequest<PurchaseOrder>('/purchase-orders/' + id, { method: 'PUT', body: JSON.stringify(value) })
export const changePurchaseOrderStatus = (id: string, value: { documentStatus?: PurchaseOrderDocumentStatus; deliveryStatus?: PurchaseOrderDeliveryStatus; paymentStatus?: PurchaseOrderPaymentStatus; reason?: string; version: number; archiveAfterVoiding?: boolean }) => apiRequest<PurchaseOrder>('/purchase-orders/' + id + '/status', { method: 'POST', body: JSON.stringify(value) })
export const recordPurchaseOrderPayment = (id: string, value: { paymentDate: string; amount: number; method: string; referenceNumber?: string; notes?: string; version: number }) => apiRequest<PurchaseOrder>('/purchase-orders/' + id + '/payments', { method: 'POST', body: JSON.stringify(value) })
export const archivePurchaseOrder = (id: string, version: number) => apiRequest<PurchaseOrder>('/purchase-orders/' + id + '/archive', { method: 'POST', body: JSON.stringify({ version }) })
export const restorePurchaseOrder = (id: string, version: number) => apiRequest<PurchaseOrder>('/purchase-orders/' + id + '/restore', { method: 'POST', body: JSON.stringify({ version }) })
