import { apiRequest } from './client'

export type StatementStatus = 'Draft' | 'Issued' | 'Partially Settled' | 'Settled' | 'Overdue' | 'Cancelled'
export type StatementSchedule = { id: string; position: number; label: string; dueDate: string; amount: number; lateChargeEnabled: boolean | null; lateChargeGraceDays: number | null; lateChargeType: 'Percentage' | 'Fixed amount' | null; lateChargeValue: number | null; version: number }
export type StatementLateCharge = { id: string; scheduleId: string; appliedDate: string; type: 'Percentage' | 'Fixed amount'; rateValue: number; calculatedAmount: number; amount: number; status: 'Applied' | 'Waived'; reason: string; createdBy: string; createdAt: string; updatedAt: string; version: number }
export type StatementPayment = { id: string; entryType: 'Payment' | 'Reversal'; reversesPaymentId: string | null; paymentDate: string; amount: number; principalAmount: number; lateChargeAmount: number; method: string; referenceNumber: string; notes: string; createdAt: string; createdBy: string }
export type StatementQuotation = { id: string; quotationId: string | null; quotationNumber: string; quotationDate: string; subject: string; projectLocation: string; subtotalAmount: number; vatEnabled: boolean; vatAmount: number; totalAmount: number; items: Array<{ id: string; itemId: string | null; variantId: string | null; photo: string; itemName: string; variantLabel: string; productCode: string; unitOfMeasure: string; quantity: number; unitPrice: number; amount: number }>; charges: Array<{ id: string; label: string; amount: number; position: number }> }
export type Statement = { id: string; soaNumber: string; statementDate: string; coverageFrom: string; coverageTo: string; dueDate: string; clientId: string | null; clientName: string; contactPerson: string; openingBalance: number; totalCharges: number; totalPayments: number; balance: number; paymentArrangement: 'Full payment' | 'Installment' | 'Custom schedule'; paymentFrequency: 'Weekly' | 'Every 2 weeks' | 'Monthly' | 'Quarterly' | 'Custom'; lateChargeEnabled: boolean; lateChargeGraceDays: number; lateChargeType: 'Percentage' | 'Fixed amount'; lateChargeValue: number; status: StatementStatus; notes: string; terms: string; voidReason: string | null; quotations: StatementQuotation[]; paymentSchedule: StatementSchedule[]; lateCharges: StatementLateCharge[]; payments: StatementPayment[]; createdAt: string; updatedAt: string; archivedAt: string | null; version: number }
export type SaveStatement = { statementDate: string; coverageFrom: string; coverageTo: string; dueDate: string; clientId: string; contactPerson: string; openingBalance: number; paymentArrangement: Statement['paymentArrangement']; paymentFrequency: Statement['paymentFrequency']; lateChargeEnabled: boolean; lateChargeGraceDays: number; lateChargeType: Statement['lateChargeType']; lateChargeValue: number; notes: string; terms: string; quotationIds: string[]; paymentSchedule: Array<{ label: string; dueDate: string; amount: number; lateChargeEnabled: boolean | null; lateChargeGraceDays: number | null; lateChargeType: Statement['lateChargeType'] | null; lateChargeValue: number | null }>; intent: 'draft' | 'issue' | 'preserve'; version?: number }
export type StatementPage = { items: Statement[]; page: number; pageSize: number; total: number }

export const listStatements = (query: { search?: string; status?: StatementStatus; archivedOnly?: boolean; page?: number; pageSize?: number } = {}) => { const values = new URLSearchParams(); if (query.search) values.set('search', query.search); if (query.status) values.set('status', query.status); if (query.archivedOnly) values.set('archivedOnly', 'true'); values.set('page', String(query.page ?? 1)); values.set('pageSize', String(query.pageSize ?? 100)); return apiRequest<StatementPage>(`/statements?${values}`) }
export const createStatement = (value: SaveStatement) => apiRequest<Statement>('/statements', { method: 'POST', body: JSON.stringify(value) })
export const updateStatement = (id: string, value: SaveStatement) => apiRequest<Statement>(`/statements/${id}`, { method: 'PUT', body: JSON.stringify(value) })
export const changeStatementStatus = (id: string, value: { status: StatementStatus; reason?: string; version: number; archiveAfterVoiding?: boolean }) => apiRequest<Statement>(`/statements/${id}/status`, { method: 'POST', body: JSON.stringify(value) })
export const archiveStatement = (id: string, version: number) => apiRequest<Statement>(`/statements/${id}/archive`, { method: 'POST', body: JSON.stringify({ version }) })
export const restoreStatement = (id: string, version: number) => apiRequest<Statement>(`/statements/${id}/restore`, { method: 'POST', body: JSON.stringify({ version }) })
export const applyStatementLateCharge = (id: string, scheduleId: string, version: number) => apiRequest<Statement>(`/statements/${id}/schedules/${scheduleId}/late-charge`, { method: 'POST', body: JSON.stringify({ version }) })
export const waiveStatementLateCharge = (id: string, scheduleId: string, reason: string, version: number) => apiRequest<Statement>(`/statements/${id}/schedules/${scheduleId}/late-charge/waive`, { method: 'POST', body: JSON.stringify({ reason, version }) })
export const recordStatementPayment = (id: string, value: { paymentDate: string; amount: number; method: string; referenceNumber: string; notes: string; idempotencyKey: string; version: number }) => apiRequest<Statement>(`/statements/${id}/payments`, { method: 'POST', body: JSON.stringify(value) })
export const reverseStatementPayment = (id: string, paymentId: string, value: { reversalDate: string; reason: string; version: number }) => apiRequest<Statement>(`/statements/${id}/payments/${paymentId}/reverse`, { method: 'POST', body: JSON.stringify(value) })
