import type { jsPDF as JsPdfDocument } from "jspdf";
import type { Quotation } from "../../features/quotations/QuotationsPage";
import type {
  StatementOfAccount,
  StatementStatus,
} from "../../features/statement-of-account/statementOfAccountTypes";
import { loadDocumentDefaults, loadLateChargePolicy, type CompanyProfile } from "../../features/settings/settingsStorage";

export type PurchaseOrderPdfLine = {
  id: string;
  itemName: string;
  variantLabel: string;
  productCode: string;
  unitOfMeasure: string;
  quantity: number;
  unitCost: number;
};

export type PurchaseOrderPdf = {
  poNumber: string;
  date: string;
  subject: string;
  modeOfPayment: string;
  paymentTerm: string;
  deliveryLocation: string;
  modeOfDelivery: string;
  items: PurchaseOrderPdfLine[];
  subtotalAmount: number;
  vatEnabled: boolean;
  vatAmount: number;
  otherCharges: Array<{ id: string; label: string; amount: number }>;
  totalAmount: number;
};

export type PurchaseOrderPdfSupplier = {
  name: string;
  address: string;
  contactPerson: string;
  phone: string;
  email: string;
};

type PdfKind = "QUOTATION" | "PURCHASE ORDER" | "STATEMENT OF ACCOUNT";
type Align = "left" | "center" | "right";
type TableColumn = { label: string; width: number; align?: Align };
type PdfContext = {
  doc: JsPdfDocument;
  kind: PdfKind;
  reference: string;
  y: number;
};

const navy: [number, number, number] = [0, 20, 63];
const orange: [number, number, number] = [249, 115, 22];
const ink: [number, number, number] = [35, 50, 74];
const muted: [number, number, number] = [104, 119, 139];
const border: [number, number, number] = [220, 227, 237];
const soft: [number, number, number] = [248, 250, 252];
const pageWidth = 210;
const margin = 14;
const contentWidth = pageWidth - margin * 2;
const bottomLimit = 278;

function clean(value: string | number | undefined | null) {
  return String(value ?? "")
    .replace(/₱/g, "PHP ")
    .replace(/[–—]/g, "-")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/[•·]/g, "-")
    .replace(/−/g, "-");
}

function wrapText(
  doc: JsPdfDocument,
  value: string | number,
  width: number,
  maxLines = Number.POSITIVE_INFINITY,
) {
  const result = doc.splitTextToSize(clean(value), width) as unknown;
  if (!Array.isArray(result)) return [clean(value)];
  return result.map((line) => String(line)).slice(0, maxLines);
}

function money(value: number) {
  return `PHP ${new Intl.NumberFormat("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(value) || 0)}`;
}

function date(value: string) {
  if (!value) return "Not provided";
  const parsed = new Date(`${value.slice(0, 10)}T00:00:00`);
  return Number.isNaN(parsed.getTime())
    ? clean(value)
    : new Intl.DateTimeFormat("en-PH", {
        month: "short",
        day: "numeric",
        year: "numeric",
      }).format(parsed);
}

function safeFilename(value: string) {
  return (
    clean(value)
      .trim()
      .replace(/[^a-zA-Z0-9._-]+/g, "-")
      .replace(/^-+|-+$/g, "") || "document"
  );
}

export function downloadDocumentBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1_000);
}

async function loadLogo() {
  try {
    const response = await fetch("/images/adiel-logo-flat.png");
    if (!response.ok) return "";
    const blob = await response.blob();
    return await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () =>
        resolve(typeof reader.result === "string" ? reader.result : "");
      reader.onerror = () =>
        reject(reader.error ?? new Error("The company logo could not be read."));
      reader.readAsDataURL(blob);
    });
  } catch {
    return "";
  }
}

function companyContactLine(profile: CompanyProfile) {
  return [
    profile.mainOfficeNumber && `Main: ${profile.mainOfficeNumber}`,
    profile.clientRelationsNumber &&
      `Client relations: ${profile.clientRelationsNumber}`,
    profile.accountsNumber && `Accounts: ${profile.accountsNumber}`,
  ]
    .filter(Boolean)
    .join("  |  ");
}

async function createDocument(
  kind: PdfKind,
  reference: string,
  profile: CompanyProfile,
): Promise<PdfContext> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
    compress: true,
  });
  doc.setProperties({
    title: `${reference} - ${kind}`,
    subject: `${kind} generated by the ADIEL Operations System`,
    author: profile.companyName || "ADIEL Construction Supplies",
    creator: "ADIEL Operations System",
  });

  doc.setFillColor(...navy);
  doc.rect(margin, 9, contentWidth * 0.78, 2.2, "F");
  doc.setFillColor(...orange);
  doc.rect(margin + contentWidth * 0.78, 9, contentWidth * 0.22, 2.2, "F");

  const logo = await loadLogo();
  if (logo) doc.addImage(logo, "PNG", margin, 15, 24, 24, undefined, "FAST");
  else {
    doc.setFillColor(...navy);
    doc.roundedRect(margin, 15, 24, 24, 2, 2, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("ADIEL", margin + 12, 29, { align: "center" });
  }

  const companyX = margin + 29;
  doc.setTextColor(...navy);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(
    clean(profile.companyName || "ADIEL CONSTRUCTION SUPPLIES"),
    companyX,
    19,
    { maxWidth: 88 },
  );
  doc.setTextColor(...muted);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.2);
  const addressLines = wrapText(
    doc,
    profile.address || "Company address not configured",
    88,
    2,
  );
  doc.text(addressLines, companyX, 24);
  doc.setFontSize(6.5);
  const contactLines = wrapText(
    doc,
    companyContactLine(profile) || "Contact numbers not configured",
    88,
    2,
  );
  doc.text(contactLines, companyX, 30.5, { lineHeightFactor: 1.05 });
  doc.text(
    clean(
      [profile.email, profile.tin && `TIN: ${profile.tin}`]
        .filter(Boolean)
        .join("  |  ") || "Company email and TIN not configured",
    ),
    companyX,
    38.5,
    { maxWidth: 88 },
  );

  doc.setDrawColor(...orange);
  doc.setLineWidth(1.2);
  doc.line(145, 15, 145, 40);
  doc.setTextColor(...orange);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.text(kind, 150, 19);
  doc.setTextColor(...navy);
  doc.setFontSize(15);
  const kindLines = wrapText(doc, kind, 44);
  doc.text(kindLines, 150, 26);
  doc.setFontSize(8);
  doc.text(clean(reference), 150, 38);

  doc.setDrawColor(...border);
  doc.setLineWidth(0.35);
  doc.line(margin, 45, pageWidth - margin, 45);
  return { doc, kind, reference, y: 51 };
}

function drawContinuationHeader(context: PdfContext) {
  const { doc, kind, reference } = context;
  doc.setFillColor(...navy);
  doc.rect(margin, 10, contentWidth, 10, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text(kind, margin + 4, 16.4);
  doc.setFont("helvetica", "normal");
  doc.text(clean(reference), pageWidth - margin - 4, 16.4, { align: "right" });
  context.y = 27;
}

function ensureSpace(context: PdfContext, height: number) {
  if (context.y + height <= bottomLimit) return;
  context.doc.addPage();
  drawContinuationHeader(context);
}

function sectionTitle(context: PdfContext, title: string) {
  ensureSpace(context, 10);
  const { doc } = context;
  doc.setFillColor(...orange);
  doc.roundedRect(margin, context.y + 1.1, 12, 1.7, 0.8, 0.8, "F");
  doc.setTextColor(...navy);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text(clean(title).toUpperCase(), margin + 16, context.y + 3.2);
  context.y += 8;
}

function infoGrid(
  context: PdfContext,
  entries: Array<{ label: string; value: string }>,
  columns = 2,
) {
  const { doc } = context;
  const gap = 3;
  const cellWidth = (contentWidth - gap * (columns - 1)) / columns;
  const rows = Math.ceil(entries.length / columns);
  for (let row = 0; row < rows; row += 1) {
    const slice = entries.slice(row * columns, row * columns + columns);
    const heights = slice.map((entry) =>
      Math.max(
        15,
        wrapText(doc, entry.value || "Not provided", cellWidth - 8).length *
          3.8 +
          10,
      ),
    );
    const rowHeight = Math.max(...heights);
    ensureSpace(context, rowHeight + 3);
    slice.forEach((entry, column) => {
      const x = margin + column * (cellWidth + gap);
      doc.setFillColor(...soft);
      doc.setDrawColor(...border);
      doc.roundedRect(x, context.y, cellWidth, rowHeight, 2, 2, "FD");
      doc.setTextColor(...muted);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6.5);
      doc.text(clean(entry.label).toUpperCase(), x + 4, context.y + 5);
      doc.setTextColor(...ink);
      doc.setFontSize(8.5);
      doc.text(
        wrapText(doc, entry.value || "Not provided", cellWidth - 8),
        x + 4,
        context.y + 10,
      );
    });
    context.y += rowHeight + 3;
  }
}

function subjectBox(context: PdfContext, label: string, value: string) {
  if (!value) return;
  const { doc } = context;
  const lines = wrapText(doc, value, contentWidth - 13);
  const height = Math.max(13, lines.length * 4 + 8);
  ensureSpace(context, height + 3);
  doc.setFillColor(255, 247, 237);
  doc.setDrawColor(254, 215, 170);
  doc.roundedRect(margin, context.y, contentWidth, height, 2, 2, "FD");
  doc.setFillColor(...orange);
  doc.rect(margin, context.y, 2.2, height, "F");
  doc.setTextColor(154, 52, 18);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.text(clean(label).toUpperCase(), margin + 6, context.y + 5);
  doc.setTextColor(...ink);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(lines, margin + 6, context.y + 10);
  context.y += height + 3;
}

function table(context: PdfContext, columns: TableColumn[], rows: string[][]) {
  const { doc } = context;
  const headerHeight = 8;
  const drawHeader = () => {
    ensureSpace(context, headerHeight + 9);
    doc.setFillColor(...navy);
    doc.rect(margin, context.y, contentWidth, headerHeight, "F");
    let x = margin;
    columns.forEach((column) => {
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6.3);
      const textX =
        column.align === "right"
          ? x + column.width - 2.5
          : column.align === "center"
            ? x + column.width / 2
            : x + 2.5;
      doc.text(clean(column.label).toUpperCase(), textX, context.y + 5, {
        align: column.align ?? "left",
      });
      x += column.width;
    });
    context.y += headerHeight;
  };

  drawHeader();
  rows.forEach((row, rowIndex) => {
    const cellLines = row.map((cell, index) => {
      const column = columns[index] ?? columns[columns.length - 1]!;
      return wrapText(doc, cell, column.width - 5, 4);
    });
    const rowHeight = Math.max(
      9,
      ...cellLines.map((lines) => lines.length * 3.7 + 4),
    );
    if (context.y + rowHeight > bottomLimit) {
      context.doc.addPage();
      drawContinuationHeader(context);
      drawHeader();
    }
    if (rowIndex % 2 === 1) {
      doc.setFillColor(...soft);
      doc.rect(margin, context.y, contentWidth, rowHeight, "F");
    }
    doc.setDrawColor(...border);
    doc.setLineWidth(0.25);
    doc.line(
      margin,
      context.y + rowHeight,
      pageWidth - margin,
      context.y + rowHeight,
    );
    let x = margin;
    cellLines.forEach((lines, index) => {
      const column = columns[index] ?? columns[columns.length - 1]!;
      doc.setTextColor(...(index === cellLines.length - 1 ? navy : ink));
      doc.setFont(
        "helvetica",
        index === 1 || index === cellLines.length - 1 ? "bold" : "normal",
      );
      doc.setFontSize(7.2);
      const textX =
        column.align === "right"
          ? x + column.width - 2.5
          : column.align === "center"
            ? x + column.width / 2
            : x + 2.5;
      doc.text(lines, textX, context.y + 5, { align: column.align ?? "left" });
      x += column.width;
    });
    context.y += rowHeight;
  });
  context.y += 4;
}

function totals(
  context: PdfContext,
  entries: Array<{
    label: string;
    value: number;
    grand?: boolean;
    negative?: boolean;
  }>,
) {
  const { doc } = context;
  const width = 78;
  const x = pageWidth - margin - width;
  const height = entries.reduce(
    (sum, entry) => sum + (entry.grand ? 14 : 9),
    0,
  );
  ensureSpace(context, height + 5);
  let y = context.y;
  entries.forEach((entry) => {
    const rowHeight = entry.grand ? 14 : 9;
    if (entry.grand) {
      doc.setFillColor(...navy);
      doc.rect(x, y, width, rowHeight, "F");
      doc.setTextColor(255, 255, 255);
    } else {
      doc.setFillColor(...soft);
      doc.setDrawColor(...border);
      doc.rect(x, y, width, rowHeight, "FD");
      doc.setTextColor(...muted);
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(entry.grand ? 8 : 7.2);
    doc.text(
      clean(entry.label).toUpperCase(),
      x + 4,
      y + (entry.grand ? 8.7 : 5.8),
    );
    doc.setTextColor(
      ...(entry.grand
        ? ([255, 255, 255] as [number, number, number])
        : entry.negative
          ? ([5, 150, 105] as [number, number, number])
          : navy),
    );
    doc.setFontSize(entry.grand ? 11 : 8);
    doc.text(
      `${entry.negative ? "- " : ""}${money(entry.value)}`,
      x + width - 4,
      y + (entry.grand ? 8.7 : 5.8),
      { align: "right" },
    );
    y += rowHeight;
  });
  context.y = y + 5;
}

function note(context: PdfContext, label: string, value: string) {
  const { doc } = context;
  const lines = wrapText(doc, value || "None", contentWidth - 10);
  const height = Math.max(14, lines.length * 4 + 10);
  ensureSpace(context, height + 4);
  doc.setDrawColor(...border);
  doc.roundedRect(margin, context.y, contentWidth, height, 2, 2, "S");
  doc.setTextColor(...muted);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(6.5);
  doc.text(clean(label).toUpperCase(), margin + 4, context.y + 5);
  doc.setTextColor(...ink);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.text(lines, margin + 4, context.y + 10);
  context.y += height + 4;
}

function terms(context: PdfContext, value: string) {
  const entries = value
    .split(/\r?\n/)
    .map((entry) => entry.trim())
    .filter(Boolean);
  if (!entries.length) return;
  sectionTitle(context, "Terms and conditions");
  entries.forEach((entry, index) => {
    const { doc } = context;
    const lines = wrapText(doc, `${index + 1}. ${clean(entry)}`, contentWidth - 5);
    const height = lines.length * 3.7 + 2;
    ensureSpace(context, height);
    doc.setTextColor(...ink);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.2);
    doc.text(lines, margin + 2, context.y + 3);
    context.y += height;
  });
}

function finalize(context: PdfContext, footerText: string) {
  const { doc, kind, reference } = context;
  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page);
    doc.setDrawColor(...navy);
    doc.setLineWidth(0.8);
    doc.line(margin, 285, pageWidth - margin, 285);
    doc.setTextColor(...muted);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.text(
      clean(footerText || "Generated electronically by the ADIEL Operations System."),
      margin,
      290,
      { maxWidth: 105 },
    );
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...navy);
    doc.text(
      `${clean(reference)}  |  ${kind}  |  Page ${page} of ${pages}`,
      pageWidth - margin,
      290,
      { align: "right" },
    );
  }
}

export async function createQuotationPdfBlob(
  quotation: Quotation,
  profile: CompanyProfile,
) {
  const defaults = loadDocumentDefaults();
  const latePolicy = loadLateChargePolicy();
  const context = await createDocument(
    "QUOTATION",
    quotation.quotationNumber,
    profile,
  );
  sectionTitle(context, "Quotation details");
  infoGrid(context, [
    { label: "Quotation number", value: quotation.quotationNumber },
    { label: "Date issued", value: date(quotation.dateCreated) },
    { label: "Prepared for", value: quotation.clientName },
    {
      label: "Contact person",
      value: quotation.contactPerson || "Not provided",
    },
    {
      label: "Project location",
      value: quotation.projectLocation || "Not provided",
    },
    { label: "Lead time", value: quotation.leadTime || "Not provided" },
  ]);
  subjectBox(context, "Subject", quotation.subject);
  sectionTitle(context, "Quoted items");
  table(
    context,
    [
      { label: "#", width: 10, align: "center" },
      { label: "Description", width: 68 },
      { label: "Unit", width: 24 },
      { label: "Qty", width: 18, align: "right" },
      { label: "Unit price", width: 30, align: "right" },
      { label: "Amount", width: 32, align: "right" },
    ],
    quotation.items.map((line, index) => [
      String(index + 1),
      [line.itemName, line.productCode, line.variantLabel]
        .filter(Boolean)
        .join(" - "),
      line.unitOfMeasure,
      String(line.quantity),
      money(line.unitPrice),
      money(line.quantity * line.unitPrice),
    ]),
  );
  totals(context, [
    { label: "Subtotal", value: quotation.subtotalAmount },
    ...(quotation.vatEnabled
      ? [{ label: "VAT (12%)", value: quotation.vatAmount }]
      : []),
    ...quotation.otherCharges.map((charge) => ({
      label: charge.label,
      value: charge.amount,
    })),
    { label: "Grand total", value: quotation.totalAmount, grand: true },
  ]);
  terms(
    context,
    [
      quotation.leadTime && `Lead time: ${quotation.leadTime}.`,
      defaults.quotationTerms,
      latePolicy.enabled && `Late-payment condition: overdue balances may incur ${latePolicy.type === "Percentage" ? `${latePolicy.value}% interest` : `${money(latePolicy.value)} as a fixed charge`} after ${latePolicy.graceDays} grace day${latePolicy.graceDays === 1 ? "" : "s"}. The applicable schedule is confirmed in the Statement of Account.`,
    ]
      .filter(Boolean)
      .join("\n"),
  );
  finalize(context, defaults.pdfFooter);
  return context.doc.output("blob");
}

export async function downloadQuotationPdf(
  quotation: Quotation,
  profile: CompanyProfile,
) {
  const blob = await createQuotationPdfBlob(quotation, profile);
  downloadDocumentBlob(
    blob,
    `${safeFilename(quotation.quotationNumber)}-quotation.pdf`,
  );
}

export async function createPurchaseOrderPdfBlob(
  order: PurchaseOrderPdf,
  supplier: PurchaseOrderPdfSupplier,
  profile: CompanyProfile,
  notesValue: string,
  termsValue: string,
) {
  const defaults = loadDocumentDefaults();
  const context = await createDocument(
    "PURCHASE ORDER",
    order.poNumber,
    profile,
  );
  sectionTitle(context, "Order details");
  infoGrid(context, [
    { label: "PO number", value: order.poNumber },
    { label: "Order date", value: date(order.date) },
    { label: "Payment mode", value: order.modeOfPayment || "Not provided" },
    { label: "Payment terms", value: order.paymentTerm || "Not provided" },
    { label: "Delivery mode", value: order.modeOfDelivery || "Not provided" },
    {
      label: "Delivery location",
      value: order.deliveryLocation || "Not provided",
    },
  ]);
  sectionTitle(context, "Supplier");
  infoGrid(context, [
    { label: "Company name", value: supplier.name },
    {
      label: "Contact person",
      value: supplier.contactPerson || "Not provided",
    },
    { label: "Address", value: supplier.address || "Not provided" },
    {
      label: "Contact details",
      value:
        [supplier.phone, supplier.email].filter(Boolean).join(" | ") ||
        "Not provided",
    },
  ]);
  subjectBox(context, "Subject", order.subject);
  sectionTitle(context, "Order items");
  table(
    context,
    [
      { label: "#", width: 10, align: "center" },
      { label: "Description", width: 68 },
      { label: "Unit", width: 24 },
      { label: "Qty", width: 18, align: "right" },
      { label: "Unit cost", width: 30, align: "right" },
      { label: "Amount", width: 32, align: "right" },
    ],
    order.items.map((line, index) => [
      String(index + 1),
      [line.itemName, line.productCode, line.variantLabel]
        .filter(Boolean)
        .join(" - "),
      line.unitOfMeasure,
      String(line.quantity),
      money(line.unitCost),
      money(line.quantity * line.unitCost),
    ]),
  );
  totals(context, [
    { label: "Subtotal", value: order.subtotalAmount },
    ...(order.vatEnabled
      ? [{ label: "VAT (12%)", value: order.vatAmount }]
      : []),
    ...order.otherCharges.map((charge) => ({
      label: charge.label,
      value: charge.amount,
    })),
    { label: "Grand total", value: order.totalAmount, grand: true },
  ]);
  note(context, "Notes / remarks", notesValue);
  terms(context, termsValue);
  finalize(context, defaults.pdfFooter);
  return context.doc.output("blob");
}

export async function downloadPurchaseOrderPdf(
  order: PurchaseOrderPdf,
  supplier: PurchaseOrderPdfSupplier,
  profile: CompanyProfile,
  notesValue: string,
  termsValue: string,
) {
  const blob = await createPurchaseOrderPdfBlob(
    order,
    supplier,
    profile,
    notesValue,
    termsValue,
  );
  downloadDocumentBlob(
    blob,
    `${safeFilename(order.poNumber)}-purchase-order.pdf`,
  );
}

export async function createStatementOfAccountPdfBlob(
  statement: StatementOfAccount,
  effectiveStatus: StatementStatus,
  profile: CompanyProfile,
) {
  const defaults = loadDocumentDefaults();
  const context = await createDocument(
    "STATEMENT OF ACCOUNT",
    statement.soaNumber,
    profile,
  );
  sectionTitle(context, "Account details");
  infoGrid(context, [
    { label: "SOA number", value: statement.soaNumber },
    { label: "Statement date", value: date(statement.statementDate) },
    { label: "Client", value: statement.clientName },
    {
      label: "Contact person",
      value: statement.contactPerson || "Not provided",
    },
    {
      label: "Coverage period",
      value: `${date(statement.coverageFrom)} - ${date(statement.coverageTo)}`,
    },
    {
      label: "Due date / Status",
      value: `${date(statement.dueDate)} / ${effectiveStatus}`,
    },
  ]);
  sectionTitle(context, "Account activity");
  const activity = [
    ...(statement.openingBalance > 0
      ? [
          {
            date: statement.coverageFrom,
            reference: "OPENING",
            description: "Opening balance",
            charge: statement.openingBalance,
            payment: 0,
          },
        ]
      : []),
    ...statement.quotations.map((quotation) => ({
      date: quotation.dateCreated,
      reference: quotation.quotationNumber,
      description: quotation.subject || "Quotation charges",
      charge: quotation.totalAmount,
      payment: 0,
    })),
    ...statement.lateCharges
      .filter((lateCharge) => lateCharge.status === "Applied")
      .map((lateCharge) => ({
        date: lateCharge.appliedDate,
        reference: "LATE CHARGE",
        description: statement.paymentSchedule.find((entry) => entry.id === lateCharge.scheduleEntryId)?.label || "Overdue payment",
        charge: lateCharge.amount,
        payment: 0,
      })),
    ...statement.payments.map((payment) => ({
      date: payment.date,
      reference: payment.referenceNumber || "PAYMENT",
      description: `${payment.method}${payment.notes ? ` - ${payment.notes}` : ""}`,
      charge: 0,
      payment: payment.amount,
    })),
  ].sort((left, right) => left.date.localeCompare(right.date));
  let runningBalance = 0;
  table(
    context,
    [
      { label: "Date", width: 25 },
      { label: "Reference", width: 29 },
      { label: "Description", width: 56 },
      { label: "Charge", width: 24, align: "right" },
      { label: "Payment", width: 24, align: "right" },
      { label: "Balance", width: 24, align: "right" },
    ],
    activity.map((entry) => {
      runningBalance += entry.charge - entry.payment;
      return [
        date(entry.date),
        entry.reference,
        entry.description,
        entry.charge ? money(entry.charge) : "-",
        entry.payment ? money(entry.payment) : "-",
        money(runningBalance),
      ];
    }),
  );
  totals(context, [
    { label: "Opening balance", value: statement.openingBalance },
    { label: "Quotation charges", value: statement.totalCharges },
    {
      label: "Payments received",
      value: statement.totalPayments,
      negative: true,
    },
    { label: "Balance due", value: statement.balance, grand: true },
  ]);
  if (statement.paymentSchedule.length) {
    sectionTitle(context, "Payment schedule");
    table(
      context,
      [
        { label: "Installment", width: 50 },
        { label: "Due date", width: 32 },
        { label: "Amount", width: 36, align: "right" },
        { label: "Late-payment rule", width: 64 },
      ],
      statement.paymentSchedule.map((entry) => {
        const policy = entry.lateChargePolicy ?? statement.lateChargePolicy;
        const rule = !policy.enabled
          ? "No late charge"
          : `${policy.type === "Percentage" ? `${policy.value}% interest` : `${money(policy.value)} fixed`} after ${policy.graceDays} grace day${policy.graceDays === 1 ? "" : "s"}`;
        return [entry.label, date(entry.dueDate), money(entry.amount), rule];
      }),
    );
  }
  note(
    context,
    "Notes / payment instructions",
    [defaults.statementPaymentInstructions, statement.notes]
      .filter(Boolean)
      .join("\n\n"),
  );
  finalize(context, defaults.pdfFooter);
  return context.doc.output("blob");
}

export async function downloadStatementOfAccountPdf(
  statement: StatementOfAccount,
  effectiveStatus: StatementStatus,
  profile: CompanyProfile,
) {
  const blob = await createStatementOfAccountPdfBlob(
    statement,
    effectiveStatus,
    profile,
  );
  downloadDocumentBlob(
    blob,
    `${safeFilename(statement.soaNumber)}-statement-of-account.pdf`,
  );
}
