import type { jsPDF as JsPdfDocument } from "jspdf";
import type { Quotation } from "../../features/quotations/QuotationsPage";
import type {
  StatementOfAccount,
  StatementStatus,
} from "../../features/statement-of-account/statementOfAccountTypes";
import { loadDocumentDefaults, loadLateChargePolicy, type CompanyProfile } from "../../features/settings/settingsStorage";

export type PurchaseOrderPdfLine = {
  id: string;
  itemName: string;
  variantLabel: string;
  productCode: string;
  unitOfMeasure: string;
  quantity: number;
  unitCost: number;
};

export type PurchaseOrderPdf = {
  poNumber: string;
  date: string;
  subject: string;
  modeOfPayment: string;
  paymentTerm: string;
  deliveryLocation: string;
  modeOfDelivery: string;
  items: PurchaseOrderPdfLine[];
  subtotalAmount: number;
  vatEnabled: boolean;
  vatAmount: number;
  otherCharges: Array<{ id: string; label: string; amount: number }>;
  totalAmount: number;
};

export type PurchaseOrderPdfSupplier = {
  name: string;
  address: string;
  contactPerson: string;
  phone: string;
  email: string;
};

type PdfKind = "QUOTATION" | "PURCHASE ORDER" | "STATEMENT OF ACCOUNT";
type Align = "left" | "center" | "right";
type TableColumn = { label: string; width: number; align?: Align };
type PdfContext = {
  doc: JsPdfDocument;
  kind: PdfKind;
  reference: string;
  y: number;
};

const navy: [number, number, number] = [0, 20, 63];
const orange: [number, number, number] = [249, 115, 22];
const ink: [number, number, number] = [35, 50, 74];
const muted: [number, number, number] = [104, 119, 139];
const border: [number, number, number] = [220, 227, 237];
const soft: [number, number, number] = [248, 250, 252];
const pageWidth = 210;
const margin = 17;
const contentWidth = pageWidth - margin * 2;
const bottomLimit = 277;

function clean(value: string | number | undefined | null) {
  return String(value ?? "")
    .replace(/₱/g, "PHP ")
    .replace(/[–—]/g, "-")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/[•·]/g, "-")
    .replace(/−/g, "-");
}

function wrapText(
  doc: JsPdfDocument,
  value: string | number,
  width: number,
  maxLines = Number.POSITIVE_INFINITY,
) {
  const result = doc.splitTextToSize(clean(value), width) as unknown;
  if (!Array.isArray(result)) return [clean(value)];
  return result.map((line) => String(line)).slice(0, maxLines);
}

function money(value: number) {
  return `PHP ${new Intl.NumberFormat("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(value) || 0)}`;
}

function amount(value: number) {
  return new Intl.NumberFormat("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(value) || 0);
}

function date(value: string) {
  if (!value) return "Not provided";
  const parsed = new Date(`${value.slice(0, 10)}T00:00:00`);
  return Number.isNaN(parsed.getTime())
    ? clean(value)
    : new Intl.DateTimeFormat("en-PH", {
        month: "short",
        day: "numeric",
        year: "numeric",
      }).format(parsed);
}

function safeFilename(value: string) {
  return (
    clean(value)
      .trim()
      .replace(/[^a-zA-Z0-9._-]+/g, "-")
      .replace(/^-+|-+$/g, "") || "document"
  );
}

export function downloadDocumentBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1_000);
}

async function loadLogo() {
  try {
    const response = await fetch("/images/adiel-logo-flat.png");
    if (!response.ok) return "";
    const blob = await response.blob();
    return await new Promise<string>((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () =>
        resolve(typeof reader.result === "string" ? reader.result : "");
      reader.onerror = () =>
        reject(reader.error ?? new Error("The company logo could not be read."));
      reader.readAsDataURL(blob);
    });
  } catch {
    return "";
  }
}

function companyContactLine(profile: CompanyProfile) {
  return [
    profile.mainOfficeNumber && `Main: ${profile.mainOfficeNumber}`,
    profile.clientRelationsNumber &&
      `Client relations: ${profile.clientRelationsNumber}`,
    profile.accountsNumber && `Accounts: ${profile.accountsNumber}`,
  ]
    .filter(Boolean)
    .join("  |  ");
}

async function createDocument(
  kind: PdfKind,
  reference: string,
  profile: CompanyProfile,
): Promise<PdfContext> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
    compress: true,
  });
  doc.setProperties({
    title: `${reference} - ${kind}`,
    subject: `${kind} generated by the ADIEL Operations System`,
    author: profile.companyName || "ADIEL Construction Supplies",
    creator: "ADIEL Operations System",
  });

  doc.setFillColor(...orange);
  doc.rect(margin, 10, 18, 1.2, "F");

  const logo = await loadLogo();
  const logoBoxWidth = 22;
  const logoBoxHeight = 20;
  const logoX = margin;
  const logoY = 15;
  if (logo) {
    const properties = doc.getImageProperties(logo);
    const sourceWidth = Number(properties.width) || 1;
    const sourceHeight = Number(properties.height) || 1;
    const scale = Math.min(
      logoBoxWidth / sourceWidth,
      logoBoxHeight / sourceHeight,
    );
    const logoWidth = sourceWidth * scale;
    const logoHeight = sourceHeight * scale;
    doc.addImage(
      logo,
      "PNG",
      logoX + (logoBoxWidth - logoWidth) / 2,
      logoY + (logoBoxHeight - logoHeight) / 2,
      logoWidth,
      logoHeight,
      undefined,
      "FAST",
    );
  } else {
    doc.setFillColor(...navy);
    doc.roundedRect(logoX + 1, logoY, 20, 20, 1.5, 1.5, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("ADIEL", logoX + logoBoxWidth / 2, 27, { align: "center" });
  }

  const companyX = margin + logoBoxWidth + 5;
  doc.setTextColor(...navy);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(
    clean(profile.companyName || "ADIEL CONSTRUCTION SUPPLIES"),
    companyX,
    18.5,
    { maxWidth: 92 },
  );
  doc.setTextColor(...muted);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.1);
  const addressLines = wrapText(
    doc,
    profile.address || "Company address not configured",
    92,
    2,
  );
  doc.text(addressLines, companyX, 23.2, { lineHeightFactor: 1.1 });
  doc.setFontSize(6.8);
  const contactLines = wrapText(
    doc,
    companyContactLine(profile) || "Contact numbers not configured",
    92,
    2,
  );
  doc.text(contactLines, companyX, 29.5, { lineHeightFactor: 1.08 });
  doc.text(
    clean(
      [profile.email, profile.tin && `TIN: ${profile.tin}`]
        .filter(Boolean)
        .join("  |  ") || "Company email and TIN not configured",
    ),
    companyX,
    36,
    { maxWidth: 92 },
  );

  doc.setTextColor(...navy);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(kind === "STATEMENT OF ACCOUNT" ? 14 : 18);
  const kindLines = wrapText(doc, kind, 48, 2);
  doc.text(kindLines, pageWidth - margin, 20, { align: "right" });
  const kindHeight = Math.max(1, kindLines.length) * 5.2;
  doc.setTextColor(...muted);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.2);
  doc.text(clean(reference), pageWidth - margin, 21.5 + kindHeight, { align: "right" });

  doc.setDrawColor(...border);
  doc.setLineWidth(0.3);
  doc.line(margin, 43, pageWidth - margin, 43);
  return { doc, kind, reference, y: 49 };
}

function drawContinuationHeader(context: PdfContext) {
  const { doc, kind, reference } = context;
  doc.setTextColor(...navy);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.text(kind, margin, 16);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...muted);
  doc.text(clean(reference), pageWidth - margin, 16, { align: "right" });
  doc.setDrawColor(...border);
  doc.setLineWidth(0.3);
  doc.line(margin, 21, pageWidth - margin, 21);
  context.y = 28;
}

function ensureSpace(context: PdfContext, height: number) {
  if (context.y + height <= bottomLimit) return;
  context.doc.addPage();
  drawContinuationHeader(context);
}

function sectionTitle(context: PdfContext, title: string) {
  ensureSpace(context, 11);
  const { doc } = context;
  doc.setTextColor(...navy);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.2);
  doc.text(clean(title), margin, context.y + 3.5);
  doc.setDrawColor(...border);
  doc.setLineWidth(0.25);
  doc.line(margin, context.y + 7, pageWidth - margin, context.y + 7);
  context.y += 11;
}

type DetailEntry = { label: string; value: string };

function detailColumns(
  context: PdfContext,
  left: { title: string; entries: DetailEntry[] },
  right: { title: string; entries: DetailEntry[] },
) {
  const { doc } = context;
  const gap = 14;
  const columnWidth = (contentWidth - gap) / 2;
  const columnHeight = (entries: DetailEntry[]) => entries.reduce((total, entry) => total + Math.max(13, wrapText(doc, entry.value || "Not provided", columnWidth).length * 4 + 8), 9);
  const height = Math.max(columnHeight(left.entries), columnHeight(right.entries));
  ensureSpace(context, height + 5);
  const startY = context.y;

  [left, right].forEach((column, columnIndex) => {
    const x = margin + columnIndex * (columnWidth + gap);
    let y = startY;
    doc.setFillColor(...orange);
    doc.rect(x, y, 10, 1, "F");
    doc.setTextColor(...navy);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.2);
    doc.text(clean(column.title), x, y + 6);
    y += 10;
    column.entries.forEach((entry) => {
      const lines = wrapText(doc, entry.value || "Not provided", columnWidth);
      const entryHeight = Math.max(13, lines.length * 4 + 8);
      doc.setTextColor(...muted);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6.7);
      doc.text(clean(entry.label).toUpperCase(), x, y + 3.5);
      doc.setTextColor(...ink);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.7);
      doc.text(lines, x, y + 8.5, { lineHeightFactor: 1.06 });
      doc.setDrawColor(...border);
      doc.setLineWidth(0.2);
      doc.line(x, y + entryHeight - 1, x + columnWidth, y + entryHeight - 1);
      y += entryHeight;
    });
  });
  context.y = startY + height + 5;
}

function amountDueSummary(context: PdfContext, amount: number, dueDate: string, status: string) {
  const { doc } = context;
  const height = 22;
  ensureSpace(context, height + 5);
  doc.setFillColor(244, 247, 251);
  doc.rect(margin, context.y, contentWidth, height, "F");
  doc.setFillColor(...orange);
  doc.rect(margin, context.y, 1.5, height, "F");
  doc.setTextColor(...muted);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(6.8);
  doc.text("BALANCE DUE", margin + 6, context.y + 6);
  doc.setTextColor(...navy);
  doc.setFontSize(15);
  doc.text(money(amount), margin + 6, context.y + 15);
  doc.setTextColor(...muted);
  doc.setFontSize(6.8);
  doc.text("DUE DATE", pageWidth - margin - 48, context.y + 6);
  doc.setTextColor(...ink);
  doc.setFontSize(8.8);
  doc.text(date(dueDate), pageWidth - margin - 48, context.y + 12);
  doc.setTextColor(...muted);
  doc.setFontSize(6.8);
  doc.text("STATUS", pageWidth - margin, context.y + 6, { align: "right" });
  doc.setTextColor(...navy);
  doc.setFontSize(8.8);
  doc.text(clean(status), pageWidth - margin, context.y + 12, { align: "right" });
  context.y += height + 5;
}

function subjectBox(context: PdfContext, label: string, value: string) {
  if (!value) return;
  const { doc } = context;
  const lines = wrapText(doc, value, contentWidth);
  const height = Math.max(14, lines.length * 4.2 + 9);
  ensureSpace(context, height + 3);
  doc.setDrawColor(...border);
  doc.setLineWidth(0.25);
  doc.line(margin, context.y + height, pageWidth - margin, context.y + height);
  doc.setTextColor(...muted);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(6.8);
  doc.text(clean(label).toUpperCase(), margin, context.y + 4);
  doc.setTextColor(...ink);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(lines, margin, context.y + 9);
  context.y += height + 3;
}

function table(context: PdfContext, columns: TableColumn[], rows: string[][]) {
  const { doc } = context;
  const suppliedWidth = columns.reduce((total, column) => total + column.width, 0) || contentWidth;
  const layoutColumns = columns.map((column) => ({ ...column, width: column.width * (contentWidth / suppliedWidth) }));
  const headerHeight = 9;
  const drawHeader = () => {
    ensureSpace(context, headerHeight + 9);
    doc.setFillColor(...soft);
    doc.rect(margin, context.y, contentWidth, headerHeight, "F");
    doc.setDrawColor(...border);
    doc.setLineWidth(0.3);
    doc.line(margin, context.y + headerHeight, pageWidth - margin, context.y + headerHeight);
    let x = margin;
    layoutColumns.forEach((column) => {
      doc.setTextColor(...navy);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6.8);
      const textX =
        column.align === "right"
          ? x + column.width - 2.5
          : column.align === "center"
            ? x + column.width / 2
            : x + 2.5;
      doc.text(clean(column.label).toUpperCase(), textX, context.y + 5, {
        align: column.align ?? "left",
      });
      x += column.width;
    });
    context.y += headerHeight;
  };

  drawHeader();
  rows.forEach((row, rowIndex) => {
    const cellLines = row.map((cell, index) => {
      const column = layoutColumns[index] ?? layoutColumns[layoutColumns.length - 1]!;
      return wrapText(doc, cell, column.width - 5, 4);
    });
    const rowHeight = Math.max(
      10,
      ...cellLines.map((lines) => lines.length * 4 + 4.5),
    );
    if (context.y + rowHeight > bottomLimit) {
      context.doc.addPage();
      drawContinuationHeader(context);
      drawHeader();
    }
    if (rowIndex % 2 === 1) {
      doc.setFillColor(251, 252, 254);
      doc.rect(margin, context.y, contentWidth, rowHeight, "F");
    }
    doc.setDrawColor(...border);
    doc.setLineWidth(0.25);
    doc.line(
      margin,
      context.y + rowHeight,
      pageWidth - margin,
      context.y + rowHeight,
    );
    let x = margin;
    cellLines.forEach((lines, index) => {
      const column = layoutColumns[index] ?? layoutColumns[layoutColumns.length - 1]!;
      doc.setTextColor(...(index === cellLines.length - 1 ? navy : ink));
      doc.setFont(
        "helvetica",
        index === 1 || index === cellLines.length - 1 ? "bold" : "normal",
      );
      doc.setFontSize(7.8);
      const textX =
        column.align === "right"
          ? x + column.width - 2.5
          : column.align === "center"
            ? x + column.width / 2
            : x + 2.5;
      doc.text(lines, textX, context.y + 5.8, { align: column.align ?? "left", lineHeightFactor: 1.05 });
      x += column.width;
    });
    context.y += rowHeight;
  });
  context.y += 4;
}

function totals(
  context: PdfContext,
  entries: Array<{
    label: string;
    value: number;
    grand?: boolean;
    negative?: boolean;
  }>,
) {
  const { doc } = context;
  const width = 76;
  const x = pageWidth - margin - width;
  const height = entries.reduce(
    (sum, entry) => sum + (entry.grand ? 15 : 8.5),
    0,
  );
  ensureSpace(context, height + 5);
  let y = context.y;
  entries.forEach((entry) => {
    const rowHeight = entry.grand ? 15 : 8.5;
    if (entry.grand) {
      doc.setFillColor(239, 244, 250);
      doc.rect(x, y, width, rowHeight, "F");
      doc.setDrawColor(...navy);
      doc.setLineWidth(0.8);
      doc.line(x, y, x + width, y);
      doc.setTextColor(...navy);
    } else {
      doc.setDrawColor(...border);
      doc.setLineWidth(0.2);
      doc.line(x, y + rowHeight, x + width, y + rowHeight);
      doc.setTextColor(...muted);
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(entry.grand ? 8.2 : 7.4);
    doc.text(
      clean(entry.label).toUpperCase(),
      x + 4,
      y + (entry.grand ? 9.3 : 5.6),
    );
    doc.setTextColor(
      ...(entry.grand
        ? navy
        : entry.negative
          ? ([5, 150, 105] as [number, number, number])
          : navy),
    );
    doc.setFontSize(entry.grand ? 11.5 : 8.2);
    doc.text(
      `${entry.negative ? "- " : ""}${money(entry.value)}`,
      x + width - 4,
      y + (entry.grand ? 9.3 : 5.6),
      { align: "right" },
    );
    y += rowHeight;
  });
  context.y = y + 5;
}

function note(context: PdfContext, label: string, value: string) {
  if (!value.trim()) return;
  const { doc } = context;
  const lines = wrapText(doc, value, contentWidth);
  const height = Math.max(15, lines.length * 4.2 + 10);
  ensureSpace(context, height + 4);
  doc.setDrawColor(...border);
  doc.setLineWidth(0.25);
  doc.line(margin, context.y, pageWidth - margin, context.y);
  doc.setTextColor(...muted);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(6.8);
  doc.text(clean(label).toUpperCase(), margin, context.y + 5);
  doc.setTextColor(...ink);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.2);
  doc.text(lines, margin, context.y + 10);
  context.y += height + 4;
}

function terms(context: PdfContext, value: string, title = "Terms and conditions") {
  const entries = value
    .split(/\r?\n/)
    .map((entry) => entry.trim())
    .filter(Boolean);
  if (!entries.length) return;
  const firstEntryLines = wrapText(context.doc, `1. ${clean(entries[0])}`, contentWidth - 3);
  const firstEntryHeight = firstEntryLines.length * 4.1 + 2.5;
  ensureSpace(context, 11 + firstEntryHeight);
  sectionTitle(context, title);
  entries.forEach((entry, index) => {
    const { doc } = context;
    const lines = wrapText(doc, `${index + 1}. ${clean(entry)}`, contentWidth - 3);
    const height = lines.length * 4.1 + 2.5;
    ensureSpace(context, height);
    doc.setTextColor(...ink);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(lines, margin, context.y + 3.5, { lineHeightFactor: 1.08 });
    context.y += height;
  });
}

function finalize(context: PdfContext, footerText: string) {
  const { doc, kind, reference } = context;
  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page);
    doc.setDrawColor(...border);
    doc.setLineWidth(0.3);
    doc.line(margin, 284, pageWidth - margin, 284);
    doc.setTextColor(...muted);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.text(
      clean(footerText || "Generated electronically by the ADIEL Operations System."),
      margin,
      289,
      { maxWidth: 100 },
    );
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...navy);
    doc.text(
      `${clean(reference)}  |  ${kind}  |  Page ${page} of ${pages}`,
      pageWidth - margin,
      289,
      { align: "right" },
    );
  }
}

export async function createQuotationPdfBlob(
  quotation: Quotation,
  profile: CompanyProfile,
) {
  const defaults = loadDocumentDefaults();
  const latePolicy = loadLateChargePolicy();
  const context = await createDocument(
    "QUOTATION",
    quotation.quotationNumber,
    profile,
  );
  detailColumns(
    context,
    {
      title: "Prepared for",
      entries: [
        { label: "Client", value: quotation.clientName },
        { label: "Contact person", value: quotation.contactPerson || "Not provided" },
        { label: "Project location", value: quotation.projectLocation || "Not provided" },
      ],
    },
    {
      title: "Document details",
      entries: [
        { label: "Quotation number", value: quotation.quotationNumber },
        { label: "Date issued", value: date(quotation.dateCreated) },
        { label: "Lead time", value: quotation.leadTime || "Not provided" },
      ],
    },
  );
  subjectBox(context, "Subject", quotation.subject);
  sectionTitle(context, "Quoted items");
  table(
    context,
    [
      { label: "#", width: 10, align: "center" },
      { label: "Description", width: 68 },
      { label: "Unit", width: 24 },
      { label: "Qty", width: 18, align: "right" },
      { label: "Unit price (PHP)", width: 30, align: "right" },
      { label: "Amount (PHP)", width: 32, align: "right" },
    ],
    quotation.items.map((line, index) => [
      String(index + 1),
      [line.itemName, line.productCode, line.variantLabel]
        .filter(Boolean)
        .join(" - "),
      line.unitOfMeasure,
      String(line.quantity),
      amount(line.unitPrice),
      amount(line.quantity * line.unitPrice),
    ]),
  );
  totals(context, [
    { label: "Subtotal", value: quotation.subtotalAmount },
    ...(quotation.vatEnabled
      ? [{ label: "VAT (12%)", value: quotation.vatAmount }]
      : []),
    ...quotation.otherCharges.map((charge) => ({
      label: charge.label,
      value: charge.amount,
    })),
    { label: "Grand total", value: quotation.totalAmount, grand: true },
  ]);
  note(context, "Notes / remarks", quotation.notes);
  terms(context, [quotation.terms, latePolicy.enabled && `Late-payment condition: overdue balances may incur ${latePolicy.type === "Percentage" ? `${latePolicy.value}% interest` : `${money(latePolicy.value)} as a fixed charge`} after ${latePolicy.graceDays} grace day${latePolicy.graceDays === 1 ? "" : "s"}. The applicable schedule is confirmed in the Statement of Account.`].filter(Boolean).join("\n"));
  finalize(context, defaults.pdfFooter);
  return context.doc.output("blob");
}

export async function downloadQuotationPdf(
  quotation: Quotation,
  profile: CompanyProfile,
) {
  const blob = await createQuotationPdfBlob(quotation, profile);
  downloadDocumentBlob(
    blob,
    `${safeFilename(quotation.quotationNumber)}-quotation.pdf`,
  );
}

export async function createPurchaseOrderPdfBlob(
  order: PurchaseOrderPdf,
  supplier: PurchaseOrderPdfSupplier,
  profile: CompanyProfile,
  notesValue: string,
  termsValue: string,
) {
  const defaults = loadDocumentDefaults();
  const context = await createDocument(
    "PURCHASE ORDER",
    order.poNumber,
    profile,
  );
  detailColumns(
    context,
    {
      title: "Supplier",
      entries: [
        { label: "Company name", value: supplier.name },
        { label: "Contact person", value: supplier.contactPerson || "Not provided" },
        { label: "Address", value: supplier.address || "Not provided" },
        { label: "Contact details", value: [supplier.phone, supplier.email].filter(Boolean).join(" | ") || "Not provided" },
      ],
    },
    {
      title: "Order details",
      entries: [
        { label: "PO number", value: order.poNumber },
        { label: "Order date", value: date(order.date) },
        { label: "Payment", value: [order.modeOfPayment, order.paymentTerm].filter(Boolean).join(" | ") || "Not provided" },
        { label: "Delivery", value: [order.modeOfDelivery, order.deliveryLocation].filter(Boolean).join(" | ") || "Not provided" },
      ],
    },
  );
  subjectBox(context, "Subject", order.subject);
  sectionTitle(context, "Order items");
  table(
    context,
    [
      { label: "#", width: 10, align: "center" },
      { label: "Description", width: 68 },
      { label: "Unit", width: 24 },
      { label: "Qty", width: 18, align: "right" },
      { label: "Unit cost (PHP)", width: 30, align: "right" },
      { label: "Amount (PHP)", width: 32, align: "right" },
    ],
    order.items.map((line, index) => [
      String(index + 1),
      [line.itemName, line.productCode, line.variantLabel]
        .filter(Boolean)
        .join(" - "),
      line.unitOfMeasure,
      String(line.quantity),
      amount(line.unitCost),
      amount(line.quantity * line.unitCost),
    ]),
  );
  totals(context, [
    { label: "Subtotal", value: order.subtotalAmount },
    ...(order.vatEnabled
      ? [{ label: "VAT (12%)", value: order.vatAmount }]
      : []),
    ...order.otherCharges.map((charge) => ({
      label: charge.label,
      value: charge.amount,
    })),
    { label: "Grand total", value: order.totalAmount, grand: true },
  ]);
  note(context, "Notes / remarks", notesValue);
  terms(context, termsValue);
  finalize(context, defaults.pdfFooter);
  return context.doc.output("blob");
}

export async function downloadPurchaseOrderPdf(
  order: PurchaseOrderPdf,
  supplier: PurchaseOrderPdfSupplier,
  profile: CompanyProfile,
  notesValue: string,
  termsValue: string,
) {
  const blob = await createPurchaseOrderPdfBlob(
    order,
    supplier,
    profile,
    notesValue,
    termsValue,
  );
  downloadDocumentBlob(
    blob,
    `${safeFilename(order.poNumber)}-purchase-order.pdf`,
  );
}

export async function createStatementOfAccountPdfBlob(
  statement: StatementOfAccount,
  effectiveStatus: StatementStatus,
  profile: CompanyProfile,
) {
  const defaults = loadDocumentDefaults();
  const context = await createDocument(
    "STATEMENT OF ACCOUNT",
    statement.soaNumber,
    profile,
  );
  detailColumns(
    context,
    {
      title: "Client account",
      entries: [
        { label: "Client", value: statement.clientName },
        { label: "Contact person", value: statement.contactPerson || "Not provided" },
        { label: "Coverage period", value: `${date(statement.coverageFrom)} - ${date(statement.coverageTo)}` },
      ],
    },
    {
      title: "Statement details",
      entries: [
        { label: "SOA number", value: statement.soaNumber },
        { label: "Statement date", value: date(statement.statementDate) },
        { label: "Payment arrangement", value: statement.paymentArrangement },
      ],
    },
  );
  amountDueSummary(context, statement.balance, statement.dueDate, effectiveStatus);
  sectionTitle(context, "Account activity");
  const activity = [
    ...(statement.openingBalance > 0
      ? [
          {
            date: statement.coverageFrom,
            reference: "OPENING",
            description: "Opening balance",
            charge: statement.openingBalance,
            payment: 0,
          },
        ]
      : []),
    ...statement.quotations.map((quotation) => ({
      date: quotation.dateCreated,
      reference: quotation.quotationNumber,
      description: quotation.subject || "Quotation charges",
      charge: quotation.totalAmount,
      payment: 0,
    })),
    ...statement.lateCharges
      .filter((lateCharge) => lateCharge.status === "Applied")
      .map((lateCharge) => ({
        date: lateCharge.appliedDate,
        reference: "LATE CHARGE",
        description: statement.paymentSchedule.find((entry) => entry.id === lateCharge.scheduleEntryId)?.label || "Overdue payment",
        charge: lateCharge.amount,
        payment: 0,
      })),
    ...statement.payments.map((payment) => ({
      date: payment.date,
      reference: payment.referenceNumber || "PAYMENT",
      description: `${payment.method}${payment.notes ? ` - ${payment.notes}` : ""}`,
      charge: 0,
      payment: payment.amount,
    })),
  ].sort((left, right) => left.date.localeCompare(right.date));
  let runningBalance = 0;
  table(
    context,
    [
      { label: "Date", width: 25 },
      { label: "Reference", width: 29 },
      { label: "Description", width: 56 },
      { label: "Charge (PHP)", width: 24, align: "right" },
      { label: "Payment (PHP)", width: 24, align: "right" },
      { label: "Balance (PHP)", width: 24, align: "right" },
    ],
    activity.map((entry) => {
      runningBalance += entry.charge - entry.payment;
      return [
        date(entry.date),
        entry.reference,
        entry.description,
        entry.charge ? amount(entry.charge) : "-",
        entry.payment ? amount(entry.payment) : "-",
        amount(runningBalance),
      ];
    }),
  );
  totals(context, [
    { label: "Opening balance", value: statement.openingBalance },
    { label: "Quotation charges", value: statement.totalCharges },
    {
      label: "Payments received",
      value: statement.totalPayments,
      negative: true,
    },
    { label: "Balance due", value: statement.balance, grand: true },
  ]);
  if (statement.paymentSchedule.length) {
    sectionTitle(context, "Payment schedule");
    table(
      context,
      [
        { label: "Installment", width: 50 },
        { label: "Due date", width: 32 },
        { label: "Amount (PHP)", width: 36, align: "right" },
        { label: "Late-payment rule", width: 64 },
      ],
      statement.paymentSchedule.map((entry) => {
        const policy = entry.lateChargePolicy ?? statement.lateChargePolicy;
        const rule = !policy.enabled
          ? "No late charge"
          : `${policy.type === "Percentage" ? `${policy.value}% interest` : `${money(policy.value)} fixed`} after ${policy.graceDays} grace day${policy.graceDays === 1 ? "" : "s"}`;
        return [entry.label, date(entry.dueDate), amount(entry.amount), rule];
      }),
    );
  }
  note(context, "Notes / remarks", statement.notes);
  terms(context, statement.terms);
  finalize(context, defaults.pdfFooter);
  return context.doc.output("blob");
}

export async function downloadStatementOfAccountPdf(
  statement: StatementOfAccount,
  effectiveStatus: StatementStatus,
  profile: CompanyProfile,
) {
  const blob = await createStatementOfAccountPdfBlob(
    statement,
    effectiveStatus,
    profile,
  );
  downloadDocumentBlob(
    blob,
    `${safeFilename(statement.soaNumber)}-statement-of-account.pdf`,
  );
}
