using System.Transactions;
using AdielSystem.Application.Common;
using AdielSystem.Application.Items;
using AdielSystem.Application.Security;
using AdielSystem.Domain.Items;
using Npgsql;
using NpgsqlTypes;

namespace AdielSystem.Infrastructure.Items;

public sealed class ItemRepository(NpgsqlDataSource dataSource) : IItemRepository
{
    public async Task<ItemSearchResult> SearchAsync(ItemSearchCriteria criteria, CancellationToken token)
    {
        await using var connection = await dataSource.OpenConnectionAsync(token);
        const string where = "deleted_at is null and (@include_archived or archived_at is null) and (not @archived_only or archived_at is not null) and (@supplier_id='' or supplier_id::text=@supplier_id or exists(select 1 from public.item_variants supplier_variant where supplier_variant.item_id=items.id and supplier_variant.supplier_id::text=@supplier_id)) and (@category='' or lower(category)=lower(@category)) and (@status='' or status=@status) and (@search_pattern='' or name ilike @search_pattern escape '\\' or product_code ilike @search_pattern escape '\\' or brand ilike @search_pattern escape '\\' or category ilike @search_pattern escape '\\')";
        var records = new List<ItemRecord>();
        await using (var command = connection.CreateCommand())
        {
            command.CommandText = $"select id,supplier_id,name,photo_url,category,subcategory,brand,unit_of_measure,unit_weight,product_code,barcode,description,status,raw_cost,selling_price,last_price_update,created_at,updated_at,archived_at,version from public.items where {where} order by {SortExpression(criteria.Sort)} limit @limit offset @offset";
            AddSearchParameters(command.Parameters, criteria);
            await using var pageReader = await command.ExecuteReaderAsync(token);
            while (await pageReader.ReadAsync(token)) records.Add(ReadItemRecord(pageReader));
        }

        var itemIds = records.Select(record => record.Id).ToArray();
        await using var batch = new NpgsqlBatch(connection);
        // Load each related table once for the entire page, regardless of item/variant count.
        foreach (var sql in new[]
        {
            "select id,supplier_id,name,value,photo_url,product_code,barcode,unit_of_measure,unit_weight,status,raw_cost,selling_price,sort_order,created_at,updated_at,version,item_id from public.item_variants where item_id=any(@item_ids) order by item_id,sort_order,id",
            "select s.id,s.name,s.value,s.sort_order,s.variant_id from public.item_variant_specifications s join public.item_variants v on v.id=s.variant_id where v.item_id=any(@item_ids) order by s.variant_id,s.sort_order,s.id",
            "select id,variant_id,effective_date,previous_raw_cost,previous_selling_price,raw_cost,selling_price,reason,notes,created_at,created_by::text,item_id from public.item_price_adjustments where item_id=any(@item_ids) order by item_id,effective_date,created_at,id"
        })
        {
            var command = new NpgsqlBatchCommand(sql);
            command.Parameters.Add("item_ids", NpgsqlDbType.Array | NpgsqlDbType.Uuid).Value = itemIds;
            batch.BatchCommands.Add(command);
        }
        var countCommand = new NpgsqlBatchCommand($"select count(*) from public.items where {where}");
        AddSearchParameters(countCommand.Parameters, criteria);
        batch.BatchCommands.Add(countCommand);
        batch.BatchCommands.Add(new NpgsqlBatchCommand("select count(*),count(*) filter (where status='Active'),count(distinct lower(category)),coalesce(avg(case when selling_price > 0 then ((selling_price-raw_cost)/selling_price)*100 else 0 end),0) from public.items where deleted_at is null and archived_at is null"));

        var variants = new Dictionary<Guid, List<ItemVariant>>();
        var specifications = new Dictionary<Guid, List<ItemVariantSpecification>>();
        var adjustments = new Dictionary<Guid, List<ItemPriceAdjustment>>();
        await using var reader = await batch.ExecuteReaderAsync(token);
        while (await reader.ReadAsync(token))
        {
            var itemId = reader.GetGuid(16);
            if (!variants.TryGetValue(itemId, out var entries)) variants[itemId] = entries = [];
            entries.Add(ReadVariant(reader));
        }
        await reader.NextResultAsync(token);
        while (await reader.ReadAsync(token))
        {
            var variantId = reader.GetGuid(4);
            if (!specifications.TryGetValue(variantId, out var entries)) specifications[variantId] = entries = [];
            entries.Add(new(reader.GetGuid(0), reader.GetString(1), reader.GetString(2), reader.GetInt32(3)));
        }
        await reader.NextResultAsync(token);
        while (await reader.ReadAsync(token))
        {
            var itemId = reader.GetGuid(11);
            if (!adjustments.TryGetValue(itemId, out var entries)) adjustments[itemId] = entries = [];
            entries.Add(ReadAdjustment(reader));
        }
        await reader.NextResultAsync(token);
        await reader.ReadAsync(token);
        var total = reader.GetInt64(0);
        await reader.NextResultAsync(token);
        await reader.ReadAsync(token);
        var summary = new ItemDirectorySummary(reader.GetInt64(0), reader.GetInt64(1), reader.GetInt64(2), reader.GetDecimal(3));
        var items = records.Select(record =>
        {
            var itemVariants = variants.GetValueOrDefault(record.Id, []).Select(variant => variant with { Specifications = specifications.GetValueOrDefault(variant.Id, []) }).ToArray();
            return Rehydrate(record, itemVariants, adjustments.GetValueOrDefault(record.Id, []));
        }).ToArray();
        return new ItemSearchResult(items, total, summary);
    }

    public async Task<Item?> GetAsync(Guid id, CancellationToken token) { await using var connection = await dataSource.OpenConnectionAsync(token); return await ReadItemAsync(connection, null, id, token); }
    public async Task<bool> AreActiveCategoriesAsync(IReadOnlyList<string> categories, CancellationToken token) { await using var command = dataSource.CreateCommand("select count(*) from public.business_options where option_type='item_category' and is_active and lower(name)=any(@categories)"); command.Parameters.Add("categories", NpgsqlDbType.Array | NpgsqlDbType.Text).Value = categories.Select(value => value.ToLowerInvariant()).ToArray(); return (long)(await command.ExecuteScalarAsync(token) ?? 0L) == categories.Count; }

    public Task<Item> CreateAsync(Item item, CurrentUser actor, CancellationToken token) => ExecuteAsync(async (connection, transaction) =>
    {
        await EnsureProductCodeAvailableAsync(connection, transaction, item.ProductCode, item.Id, null, token);
        await using (var command = connection.CreateCommand()) { command.Transaction = transaction; command.CommandText = "insert into public.items (id,supplier_id,name,photo_url,category,subcategory,brand,unit_of_measure,unit_weight,product_code,barcode,description,status,raw_cost,selling_price,last_price_update,created_by,updated_by) values (@id,@supplier_id,@name,@photo_url,@category,@subcategory,@brand,@unit_of_measure,@unit_weight,@product_code,@barcode,@description,@status,@raw_cost,@selling_price,@last_price_update,@actor_id,@actor_id)"; AddItemParameters(command, item, actor.Id); await command.ExecuteNonQueryAsync(token); }
        await InsertAdjustmentAsync(connection, transaction, item.Id, null, item.LastPriceUpdate ?? DateOnly.FromDateTime(DateTime.UtcNow), item.RawCost, item.SellingPrice, item.RawCost, item.SellingPrice, "Initial price", string.Empty, actor, token);
        await InsertAuditAsync(connection, transaction, item.Id, "Created", item.Name, $"Item added under {item.Category}.", actor, item.Status.ToString(), token);
        return await RequiredAsync(connection, transaction, item.Id, token);
    }, token);

    public Task<Item> UpdateAsync(Item item, long expectedVersion, CurrentUser actor, CancellationToken token) => ExecuteAsync(async (connection, transaction) =>
    {
        var previous = await RequiredAsync(connection, transaction, item.Id, token);
        await EnsureProductCodeAvailableAsync(connection, transaction, item.ProductCode, item.Id, null, token);
        await using (var command = connection.CreateCommand()) { command.Transaction = transaction; command.CommandText = "update public.items set supplier_id=@supplier_id,name=@name,photo_url=@photo_url,category=@category,subcategory=@subcategory,brand=@brand,unit_of_measure=@unit_of_measure,unit_weight=@unit_weight,product_code=@product_code,barcode=@barcode,description=@description,status=@status,raw_cost=@raw_cost,selling_price=@selling_price,last_price_update=@last_price_update,updated_by=@actor_id where id=@id and archived_at is null and deleted_at is null and version=@version returning id"; AddItemParameters(command, item, actor.Id); command.Parameters.AddWithValue("version", expectedVersion); if (await command.ExecuteScalarAsync(token) is null) throw Stale("item"); }
        if (previous.RawCost != item.RawCost || previous.SellingPrice != item.SellingPrice) await InsertAdjustmentAsync(connection, transaction, item.Id, null, item.LastPriceUpdate ?? DateOnly.FromDateTime(DateTime.UtcNow), previous.RawCost, previous.SellingPrice, item.RawCost, item.SellingPrice, "Item details update", "Price changed while editing item details.", actor, token);
        await InsertAuditAsync(connection, transaction, item.Id, "Updated", item.Name, "Item details, sourcing, or pricing were updated.", actor, item.Status.ToString(), token);
        return await RequiredAsync(connection, transaction, item.Id, token);
    }, token);

    public Task<Item> SetArchivedAsync(Item item, long expectedVersion, bool archived, CurrentUser actor, CancellationToken token) => ExecuteAsync(async (connection, transaction) =>
    {
        await using var command = connection.CreateCommand(); command.Transaction = transaction; command.CommandText = archived ? "update public.items set archived_at=now(),archived_by=@actor_id,updated_by=@actor_id where id=@id and archived_at is null and deleted_at is null and version=@version returning id" : "update public.items set archived_at=null,archived_by=null,updated_by=@actor_id where id=@id and archived_at is not null and deleted_at is null and version=@version returning id"; command.Parameters.AddWithValue("actor_id", actor.Id); command.Parameters.AddWithValue("id", item.Id); command.Parameters.AddWithValue("version", expectedVersion); if (await command.ExecuteScalarAsync(token) is null) throw Stale("item"); await InsertAuditAsync(connection, transaction, item.Id, archived ? "Archived" : "Restored", item.Name, archived ? "Item was archived with quotation and purchasing history retained." : "Item was restored to the catalog.", actor, item.Status.ToString(), token); return await RequiredAsync(connection, transaction, item.Id, token);
    }, token);

    public Task<Item> CreateVariantAsync(Guid itemId, SaveItemVariantRequest request, CurrentUser actor, CancellationToken token) => ExecuteAsync(async (connection, transaction) =>
    {
        var item = await RequiredAsync(connection, transaction, itemId, token); var variantId = Guid.NewGuid(); await EnsureProductCodeAvailableAsync(connection, transaction, request.ProductCode?.Trim() ?? string.Empty, itemId, variantId, token);
        await InsertVariantAsync(connection, transaction, itemId, variantId, request, item.Variants.Count, token); await InsertAdjustmentAsync(connection, transaction, itemId, variantId, DateOnly.FromDateTime(DateTime.UtcNow), request.RawCost, request.SellingPrice, request.RawCost, request.SellingPrice, "Initial price", string.Empty, actor, token); await InsertAuditAsync(connection, transaction, itemId, "Created", item.Name, $"Variant {request.Name.Trim()}: {request.Value.Trim()} was added.", actor, item.Status.ToString(), token); return await RequiredAsync(connection, transaction, itemId, token);
    }, token);

    public Task<Item> UpdateVariantAsync(Guid itemId, Guid variantId, SaveItemVariantRequest request, CurrentUser actor, CancellationToken token) => ExecuteAsync(async (connection, transaction) =>
    {
        var item = await RequiredAsync(connection, transaction, itemId, token); var previous = item.Variants.SingleOrDefault(value => value.Id == variantId) ?? throw new ResourceNotFoundException("The item variant was not found."); await EnsureProductCodeAvailableAsync(connection, transaction, request.ProductCode?.Trim() ?? string.Empty, itemId, variantId, token);
        await using (var command = connection.CreateCommand()) { command.Transaction = transaction; command.CommandText = "update public.item_variants set supplier_id=@supplier_id,name=@name,value=@value,photo_url=@photo_url,product_code=@product_code,barcode=@barcode,unit_of_measure=@unit_of_measure,unit_weight=@unit_weight,status=@status,raw_cost=@raw_cost,selling_price=@selling_price where id=@id and item_id=@item_id and version=@version returning id"; AddVariantParameters(command, request, variantId, itemId); command.Parameters.AddWithValue("version", request.Version!.Value); if (await command.ExecuteScalarAsync(token) is null) throw Stale("variant"); }
        await ReplaceSpecificationsAsync(connection, transaction, variantId, request.Specifications, token); if (previous.RawCost != request.RawCost || previous.SellingPrice != request.SellingPrice) await InsertAdjustmentAsync(connection, transaction, itemId, variantId, DateOnly.FromDateTime(DateTime.UtcNow), previous.RawCost, previous.SellingPrice, request.RawCost, request.SellingPrice, "Item details update", "Price changed while editing variant details.", actor, token); await InsertAuditAsync(connection, transaction, itemId, "Updated", item.Name, $"Variant {request.Name.Trim()}: {request.Value.Trim()} was updated.", actor, item.Status.ToString(), token); return await RequiredAsync(connection, transaction, itemId, token);
    }, token);

    public Task<Item> DeleteVariantAsync(Guid itemId, Guid variantId, long expectedVersion, CurrentUser actor, CancellationToken token) => ExecuteAsync(async (connection, transaction) => { var item = await RequiredAsync(connection, transaction, itemId, token); var variant = item.Variants.SingleOrDefault(value => value.Id == variantId) ?? throw new ResourceNotFoundException("The item variant was not found."); await using var command = connection.CreateCommand(); command.Transaction = transaction; command.CommandText = "delete from public.item_variants where id=@id and item_id=@item_id and version=@version returning id"; command.Parameters.AddWithValue("id", variantId); command.Parameters.AddWithValue("item_id", itemId); command.Parameters.AddWithValue("version", expectedVersion); if (await command.ExecuteScalarAsync(token) is null) throw Stale("variant"); await InsertAuditAsync(connection, transaction, itemId, "Updated", item.Name, $"Variant {variant.Name}: {variant.Value} was removed.", actor, item.Status.ToString(), token); return await RequiredAsync(connection, transaction, itemId, token); }, token);

    public Task<Item> AddPriceAdjustmentAsync(Guid itemId, AddPriceAdjustmentRequest request, CurrentUser actor, CancellationToken token) => ExecuteAsync(async (connection, transaction) =>
    {
        var item = await RequiredAsync(connection, transaction, itemId, token); decimal previousRaw; decimal previousSelling;
        if (request.VariantId is null) { previousRaw = item.RawCost; previousSelling = item.SellingPrice; await using var command = connection.CreateCommand(); command.Transaction = transaction; command.CommandText = "update public.items set raw_cost=@raw_cost,selling_price=@selling_price,last_price_update=@effective_date,updated_by=@actor_id where id=@id and archived_at is null and deleted_at is null and version=@version returning id"; command.Parameters.AddWithValue("raw_cost", request.RawCost); command.Parameters.AddWithValue("selling_price", request.SellingPrice); command.Parameters.AddWithValue("effective_date", request.EffectiveDate); command.Parameters.AddWithValue("actor_id", actor.Id); command.Parameters.AddWithValue("id", itemId); command.Parameters.AddWithValue("version", request.ItemVersion); if (await command.ExecuteScalarAsync(token) is null) throw Stale("item"); }
        else { var variant = item.Variants.SingleOrDefault(value => value.Id == request.VariantId.Value) ?? throw new ResourceNotFoundException("The item variant was not found."); previousRaw = variant.RawCost; previousSelling = variant.SellingPrice; await using (var itemCommand = connection.CreateCommand()) { itemCommand.Transaction = transaction; itemCommand.CommandText = "update public.items set updated_by=@actor_id where id=@id and archived_at is null and deleted_at is null and version=@version returning id"; itemCommand.Parameters.AddWithValue("actor_id", actor.Id); itemCommand.Parameters.AddWithValue("id", itemId); itemCommand.Parameters.AddWithValue("version", request.ItemVersion); if (await itemCommand.ExecuteScalarAsync(token) is null) throw Stale("item"); } await using var command = connection.CreateCommand(); command.Transaction = transaction; command.CommandText = "update public.item_variants set raw_cost=@raw_cost,selling_price=@selling_price where id=@id and item_id=@item_id and version=@version returning id"; command.Parameters.AddWithValue("raw_cost", request.RawCost); command.Parameters.AddWithValue("selling_price", request.SellingPrice); command.Parameters.AddWithValue("id", request.VariantId.Value); command.Parameters.AddWithValue("item_id", itemId); command.Parameters.AddWithValue("version", request.VariantVersion!.Value); if (await command.ExecuteScalarAsync(token) is null) throw Stale("variant"); }
        if (previousRaw == request.RawCost && previousSelling == request.SellingPrice) throw new ResourceConflictException("Change the raw cost or selling price before saving."); await InsertAdjustmentAsync(connection, transaction, itemId, request.VariantId, request.EffectiveDate, previousRaw, previousSelling, request.RawCost, request.SellingPrice, request.Reason, request.Notes ?? string.Empty, actor, token); await InsertAuditAsync(connection, transaction, itemId, "Updated", item.Name, $"{request.Reason}: price was adjusted.", actor, item.Status.ToString(), token); return await RequiredAsync(connection, transaction, itemId, token);
    }, token);

    private static ItemRecord ReadItemRecord(NpgsqlDataReader reader) => new(reader.GetGuid(0), reader.IsDBNull(1) ? null : reader.GetGuid(1), reader.GetString(2), reader.IsDBNull(3) ? null : reader.GetString(3), reader.GetString(4), reader.GetString(5), reader.GetString(6), reader.GetString(7), reader.GetDecimal(8), reader.IsDBNull(9) ? string.Empty : reader.GetString(9), reader.IsDBNull(10) ? string.Empty : reader.GetString(10), reader.GetString(11), reader.GetString(12), reader.GetDecimal(13), reader.GetDecimal(14), reader.IsDBNull(15) ? null : reader.GetFieldValue<DateOnly>(15), reader.GetFieldValue<DateTimeOffset>(16), reader.GetFieldValue<DateTimeOffset>(17), reader.IsDBNull(18) ? null : reader.GetFieldValue<DateTimeOffset>(18), reader.GetInt64(19));
    private static ItemVariant ReadVariant(NpgsqlDataReader reader) => new(reader.GetGuid(0), reader.IsDBNull(1) ? null : reader.GetGuid(1), reader.GetString(2), reader.GetString(3), reader.IsDBNull(4) ? null : reader.GetString(4), reader.IsDBNull(5) ? string.Empty : reader.GetString(5), reader.IsDBNull(6) ? string.Empty : reader.GetString(6), reader.GetString(7), reader.GetDecimal(8), ParseStatus(reader.GetString(9)), reader.GetDecimal(10), reader.GetDecimal(11), reader.GetInt32(12), [], reader.GetFieldValue<DateTimeOffset>(13), reader.GetFieldValue<DateTimeOffset>(14), reader.GetInt64(15));
    private static ItemPriceAdjustment ReadAdjustment(NpgsqlDataReader reader) => new(reader.GetGuid(0), reader.IsDBNull(1) ? null : reader.GetGuid(1), reader.GetFieldValue<DateOnly>(2), reader.GetDecimal(3), reader.GetDecimal(4), reader.GetDecimal(5), reader.GetDecimal(6), reader.GetString(7), reader.GetString(8), reader.GetFieldValue<DateTimeOffset>(9), reader.IsDBNull(10) ? "System" : reader.GetString(10));
    private static Item Rehydrate(ItemRecord record, IEnumerable<ItemVariant> variants, IEnumerable<ItemPriceAdjustment> adjustments) => Item.Rehydrate(record.Id, record.SupplierId, record.Name, record.Photo, record.Category, record.Subcategory, record.Brand, record.Unit, record.Weight, record.ProductCode, record.Barcode, record.Description, ParseStatus(record.Status), record.RawCost, record.SellingPrice, record.LastPriceUpdate, variants, adjustments, record.CreatedAt, record.UpdatedAt, record.ArchivedAt, record.Version);

    private static async Task<Item?> ReadItemAsync(NpgsqlConnection connection, NpgsqlTransaction? transaction, Guid id, CancellationToken token)
    {
        ItemRecord record; await using (var command = connection.CreateCommand()) { command.Transaction = transaction; command.CommandText = "select id,supplier_id,name,photo_url,category,subcategory,brand,unit_of_measure,unit_weight,product_code,barcode,description,status,raw_cost,selling_price,last_price_update,created_at,updated_at,archived_at,version from public.items where id=@id and deleted_at is null"; command.Parameters.AddWithValue("id", id); await using var reader = await command.ExecuteReaderAsync(token); if (!await reader.ReadAsync(token)) return null; record = ReadItemRecord(reader); }
        var variants = await ReadVariantsAsync(connection, transaction, id, token); var adjustments = await ReadAdjustmentsAsync(connection, transaction, id, token); return Rehydrate(record, variants, adjustments);
    }
    private static async Task<IReadOnlyList<ItemVariant>> ReadVariantsAsync(NpgsqlConnection connection, NpgsqlTransaction? transaction, Guid itemId, CancellationToken token) { var results = new List<ItemVariant>(); await using var command = connection.CreateCommand(); command.Transaction = transaction; command.CommandText = "select id,supplier_id,name,value,photo_url,product_code,barcode,unit_of_measure,unit_weight,status,raw_cost,selling_price,sort_order,created_at,updated_at,version from public.item_variants where item_id=@item_id order by sort_order,id"; command.Parameters.AddWithValue("item_id", itemId); await using var reader = await command.ExecuteReaderAsync(token); while (await reader.ReadAsync(token)) results.Add(ReadVariant(reader)); reader.Close(); for (var index = 0; index < results.Count; index++) results[index] = results[index] with { Specifications = await ReadSpecificationsAsync(connection, transaction, results[index].Id, token) }; return results; }
    private static async Task<IReadOnlyList<ItemVariantSpecification>> ReadSpecificationsAsync(NpgsqlConnection connection, NpgsqlTransaction? transaction, Guid variantId, CancellationToken token) { var results = new List<ItemVariantSpecification>(); await using var command = connection.CreateCommand(); command.Transaction = transaction; command.CommandText = "select id,name,value,sort_order from public.item_variant_specifications where variant_id=@variant_id order by sort_order,id"; command.Parameters.AddWithValue("variant_id", variantId); await using var reader = await command.ExecuteReaderAsync(token); while (await reader.ReadAsync(token)) results.Add(new(reader.GetGuid(0), reader.GetString(1), reader.GetString(2), reader.GetInt32(3))); return results; }
    private static async Task<IReadOnlyList<ItemPriceAdjustment>> ReadAdjustmentsAsync(NpgsqlConnection connection, NpgsqlTransaction? transaction, Guid itemId, CancellationToken token) { var results = new List<ItemPriceAdjustment>(); await using var command = connection.CreateCommand(); command.Transaction = transaction; command.CommandText = "select id,variant_id,effective_date,previous_raw_cost,previous_selling_price,raw_cost,selling_price,reason,notes,created_at,created_by::text from public.item_price_adjustments where item_id=@item_id order by effective_date,created_at,id"; command.Parameters.AddWithValue("item_id", itemId); await using var reader = await command.ExecuteReaderAsync(token); while (await reader.ReadAsync(token)) results.Add(ReadAdjustment(reader)); return results; }
    private static async Task InsertVariantAsync(NpgsqlConnection connection, NpgsqlTransaction? transaction, Guid itemId, Guid variantId, SaveItemVariantRequest request, int sortOrder, CancellationToken token) { await using var command = connection.CreateCommand(); command.Transaction = transaction; command.CommandText = "insert into public.item_variants (id,item_id,supplier_id,name,value,photo_url,product_code,barcode,unit_of_measure,unit_weight,status,raw_cost,selling_price,sort_order) values (@id,@item_id,@supplier_id,@name,@value,@photo_url,@product_code,@barcode,@unit_of_measure,@unit_weight,@status,@raw_cost,@selling_price,@sort_order)"; AddVariantParameters(command, request, variantId, itemId); command.Parameters.AddWithValue("sort_order", sortOrder); await command.ExecuteNonQueryAsync(token); await ReplaceSpecificationsAsync(connection, transaction, variantId, request.Specifications, token); }
    private static async Task ReplaceSpecificationsAsync(NpgsqlConnection connection, NpgsqlTransaction? transaction, Guid variantId, IReadOnlyList<SaveItemVariantSpecificationRequest> specifications, CancellationToken token) { await using (var delete = connection.CreateCommand()) { delete.Transaction = transaction; delete.CommandText = "delete from public.item_variant_specifications where variant_id=@variant_id"; delete.Parameters.AddWithValue("variant_id", variantId); await delete.ExecuteNonQueryAsync(token); } for (var index = 0; index < specifications.Count; index++) { var specification = specifications[index]; await using var insert = connection.CreateCommand(); insert.Transaction = transaction; insert.CommandText = "insert into public.item_variant_specifications (id,variant_id,name,value,sort_order) values (@id,@variant_id,@name,@value,@sort_order)"; insert.Parameters.AddWithValue("id", !specification.Id.HasValue || specification.Id.Value == Guid.Empty ? Guid.NewGuid() : specification.Id.Value); insert.Parameters.AddWithValue("variant_id", variantId); insert.Parameters.AddWithValue("name", specification.Name.Trim()); insert.Parameters.AddWithValue("value", specification.Value.Trim()); insert.Parameters.AddWithValue("sort_order", index); await insert.ExecuteNonQueryAsync(token); } }
    private static async Task InsertAdjustmentAsync(NpgsqlConnection connection, NpgsqlTransaction? transaction, Guid itemId, Guid? variantId, DateOnly date, decimal previousRaw, decimal previousSelling, decimal raw, decimal selling, string reason, string notes, CurrentUser actor, CancellationToken token) { await using var command = connection.CreateCommand(); command.Transaction = transaction; command.CommandText = "insert into public.item_price_adjustments (item_id,variant_id,effective_date,previous_raw_cost,previous_selling_price,raw_cost,selling_price,reason,notes,created_by) values (@item_id,@variant_id,@effective_date,@previous_raw_cost,@previous_selling_price,@raw_cost,@selling_price,@reason,@notes,@actor_id)"; command.Parameters.AddWithValue("item_id", itemId); command.Parameters.AddWithValue("variant_id", (object?)variantId ?? DBNull.Value); command.Parameters.AddWithValue("effective_date", date); command.Parameters.AddWithValue("previous_raw_cost", previousRaw); command.Parameters.AddWithValue("previous_selling_price", previousSelling); command.Parameters.AddWithValue("raw_cost", raw); command.Parameters.AddWithValue("selling_price", selling); command.Parameters.AddWithValue("reason", reason); command.Parameters.AddWithValue("notes", notes); command.Parameters.AddWithValue("actor_id", actor.Id); await command.ExecuteNonQueryAsync(token); }
    private static async Task EnsureProductCodeAvailableAsync(NpgsqlConnection connection, NpgsqlTransaction? transaction, string productCode, Guid itemId, Guid? variantId, CancellationToken token) { if (string.IsNullOrWhiteSpace(productCode)) return; await using var command = connection.CreateCommand(); command.Transaction = transaction; command.CommandText = "select exists(select 1 from public.items where lower(product_code)=lower(@product_code) and deleted_at is null and id<>@item_id union all select 1 from public.item_variants where lower(product_code)=lower(@product_code) and id<>@variant_id)"; command.Parameters.AddWithValue("product_code", productCode); command.Parameters.AddWithValue("item_id", itemId); command.Parameters.AddWithValue("variant_id", variantId ?? Guid.Empty); if ((bool)(await command.ExecuteScalarAsync(token) ?? false)) throw new ResourceConflictException("That product code is already in use."); }
    private static void AddItemParameters(NpgsqlCommand command, Item item, Guid actorId) { command.Parameters.AddWithValue("id", item.Id); command.Parameters.AddWithValue("supplier_id", (object?)item.SupplierId ?? DBNull.Value); command.Parameters.AddWithValue("name", item.Name); command.Parameters.AddWithValue("photo_url", (object?)item.PhotoPath ?? DBNull.Value); command.Parameters.AddWithValue("category", item.Category); command.Parameters.AddWithValue("subcategory", item.Subcategory); command.Parameters.AddWithValue("brand", item.Brand); command.Parameters.AddWithValue("unit_of_measure", item.UnitOfMeasure); command.Parameters.AddWithValue("unit_weight", item.UnitWeight); command.Parameters.AddWithValue("product_code", string.IsNullOrWhiteSpace(item.ProductCode) ? DBNull.Value : item.ProductCode); command.Parameters.AddWithValue("barcode", string.IsNullOrWhiteSpace(item.Barcode) ? DBNull.Value : item.Barcode); command.Parameters.AddWithValue("description", item.Description); command.Parameters.AddWithValue("status", item.Status.ToString()); command.Parameters.AddWithValue("raw_cost", item.RawCost); command.Parameters.AddWithValue("selling_price", item.SellingPrice); command.Parameters.AddWithValue("last_price_update", (object?)item.LastPriceUpdate ?? DBNull.Value); command.Parameters.AddWithValue("actor_id", actorId); }
    private static void AddVariantParameters(NpgsqlCommand command, SaveItemVariantRequest request, Guid variantId, Guid itemId) { command.Parameters.AddWithValue("id", variantId); command.Parameters.AddWithValue("item_id", itemId); command.Parameters.AddWithValue("supplier_id", (object?)request.SupplierId ?? DBNull.Value); command.Parameters.AddWithValue("name", request.Name.Trim()); command.Parameters.AddWithValue("value", request.Value.Trim()); command.Parameters.AddWithValue("photo_url", string.IsNullOrWhiteSpace(request.Photo) ? DBNull.Value : request.Photo.Trim()); command.Parameters.AddWithValue("product_code", string.IsNullOrWhiteSpace(request.ProductCode) ? DBNull.Value : request.ProductCode.Trim()); command.Parameters.AddWithValue("barcode", string.IsNullOrWhiteSpace(request.Barcode) ? DBNull.Value : request.Barcode.Trim()); command.Parameters.AddWithValue("unit_of_measure", request.UnitOfMeasure.Trim()); command.Parameters.AddWithValue("unit_weight", request.UnitWeight); command.Parameters.AddWithValue("status", request.Status.Trim()); command.Parameters.AddWithValue("raw_cost", request.RawCost); command.Parameters.AddWithValue("selling_price", request.SellingPrice); }
    private static async Task InsertAuditAsync(NpgsqlConnection connection, NpgsqlTransaction? transaction, Guid id, string action, string entity, string description, CurrentUser actor, string status, CancellationToken token) { await using var command = connection.CreateCommand(); command.Transaction = transaction; command.CommandText = "insert into public.audit_records (record_id,module,action,entity,description,actor_id,actor_name,tone,status) values (@record_id,'Items',@action,@entity,@description,@actor_id,@actor_name,@tone,@status)"; command.Parameters.AddWithValue("record_id", id); command.Parameters.AddWithValue("action", action); command.Parameters.AddWithValue("entity", entity); command.Parameters.AddWithValue("description", description); command.Parameters.AddWithValue("actor_id", actor.Id); command.Parameters.AddWithValue("actor_name", actor.Username); command.Parameters.AddWithValue("tone", action == "Created" ? "success" : "info"); command.Parameters.AddWithValue("status", status); await command.ExecuteNonQueryAsync(token); }
    private static async Task<Item> RequiredAsync(NpgsqlConnection connection, NpgsqlTransaction? transaction, Guid id, CancellationToken token) => await ReadItemAsync(connection, transaction, id, token) ?? throw new ResourceNotFoundException($"Item '{id}' was not found.");
    private static void AddSearchParameters(NpgsqlParameterCollection parameters, ItemSearchCriteria c) { parameters.AddWithValue("include_archived", c.IncludeArchived); parameters.AddWithValue("archived_only", c.ArchivedOnly); parameters.AddWithValue("supplier_id", c.SupplierId ?? string.Empty); parameters.AddWithValue("category", c.Category ?? string.Empty); parameters.AddWithValue("status", c.Status ?? string.Empty); parameters.AddWithValue("search_pattern", string.IsNullOrWhiteSpace(c.Search) ? string.Empty : "%" + EscapeLike(c.Search) + "%"); parameters.AddWithValue("limit", c.PageSize); parameters.AddWithValue("offset", (c.Page - 1) * c.PageSize); }
    private static string SortExpression(string sort) => sort switch { "name" => "name", "price" => "selling_price desc,name", _ => "updated_at desc,name" }; private static string EscapeLike(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("%", "\\%", StringComparison.Ordinal).Replace("_", "\\_", StringComparison.Ordinal); private static ItemStatus ParseStatus(string value) => value switch { "Inactive" => ItemStatus.Inactive, "Discontinued" => ItemStatus.Discontinued, _ => ItemStatus.Active }; private static ConcurrencyConflictException Stale(string subject) => new($"This {subject} changed after you opened it. Reload and try again.");
    private async Task<T> ExecuteAsync<T>(Func<NpgsqlConnection, NpgsqlTransaction?, Task<T>> action, CancellationToken token) { await using var connection = await dataSource.OpenConnectionAsync(token); await using var transaction = Transaction.Current is null ? await connection.BeginTransactionAsync(token) : null; var result = await action(connection, transaction); if (transaction is not null) await transaction.CommitAsync(token); return result; }
    private sealed record ItemRecord(Guid Id, Guid? SupplierId, string Name, string? Photo, string Category, string Subcategory, string Brand, string Unit, decimal Weight, string ProductCode, string Barcode, string Description, string Status, decimal RawCost, decimal SellingPrice, DateOnly? LastPriceUpdate, DateTimeOffset CreatedAt, DateTimeOffset UpdatedAt, DateTimeOffset? ArchivedAt, long Version);
}
