using System.Net;
using System.Net.Http.Json;
using AdielSystem.Application.Expenses;
using AdielSystem.Application.Settings;

namespace AdielSystem.IntegrationTests;
public sealed class AuthenticatedExpenseFlowTests
{
 [Fact]
 public async Task Owner_can_create_update_void_archive_restore_and_reject_stale_expense()
 { await using var factory=new OwnerApiFactory();using var client=factory.CreateClient();var token=TestContext.Current.CancellationToken;var categories=await client.GetFromJsonAsync<BusinessOptionDto[]>("/api/v1/settings/options?type=expense_category",token);var methods=await client.GetFromJsonAsync<BusinessOptionDto[]>("/api/v1/settings/options?type=payment_method",token);var create=await client.PostAsJsonAsync("/api/v1/expenses",new{expenseDate="2026-08-25",payee="Integration expense",category=categories!.First(x=>x.IsActive).Name,description="Test",amount=100m,paymentMethod=methods!.First(x=>x.IsActive).Name,purchaser="Owner",status="Verifying",invoiceUrl="",notes="",quotationId=(Guid?)null,quotationNumber="",projectName="",purchaseOrderId=(Guid?)null},token);Assert.Equal(HttpStatusCode.Created,create.StatusCode);var expense=await create.Content.ReadFromJsonAsync<ExpenseDto>(token);Assert.NotNull(expense);var paid=await client.PostAsJsonAsync($"/api/v1/expenses/{expense!.Id}/status",new{status="Paid",reason=(string?)null,version=expense.Version},token);paid.EnsureSuccessStatusCode();var updated=await paid.Content.ReadFromJsonAsync<ExpenseDto>(token);var stale=await client.PutAsJsonAsync($"/api/v1/expenses/{expense.Id}",new{expenseDate="2026-08-25",payee="Integration expense",category=expense.Category,description="stale",amount=100m,paymentMethod=expense.PaymentMethod,purchaser="Owner",status="Paid",invoiceUrl="",notes="",quotationId=(Guid?)null,quotationNumber="",projectName="",purchaseOrderId=(Guid?)null,version=expense.Version},token);Assert.Equal(HttpStatusCode.Conflict,stale.StatusCode);var cancel=await client.PostAsJsonAsync($"/api/v1/expenses/{expense.Id}/status",new{status="Cancelled",reason="Correction",version=updated!.Version},token);cancel.EnsureSuccessStatusCode();var cancelled=await cancel.Content.ReadFromJsonAsync<ExpenseDto>(token);var archive=await client.PostAsJsonAsync($"/api/v1/expenses/{expense.Id}/archive",new{version=cancelled!.Version},token);archive.EnsureSuccessStatusCode();var archived=await archive.Content.ReadFromJsonAsync<ExpenseDto>(token);var restore=await client.PostAsJsonAsync($"/api/v1/expenses/{expense.Id}/restore",new{version=archived!.Version},token);restore.EnsureSuccessStatusCode();Assert.Null((await restore.Content.ReadFromJsonAsync<ExpenseDto>(token))!.ArchivedAt); }
}
