using System.Transactions;
using AdielSystem.Application.Common;
using AdielSystem.Application.PurchaseOrders;
using AdielSystem.Application.Security;
using Npgsql;

namespace AdielSystem.Infrastructure.PurchaseOrders;

public sealed class PurchaseOrderRepository(NpgsqlDataSource dataSource) : IPurchaseOrderRepository
{
    private const decimal VatRate = .12m;
    public async Task<PurchaseOrderPageDto> ListAsync(string search, string? status, bool archivedOnly, int page, int pageSize, CancellationToken token)
    {
        await using var c = await dataSource.OpenConnectionAsync(token); const string where = "deleted_at is null and (@archived = (archived_at is not null)) and (@status='' or status=@status) and (@search='' or po_number ilike @search or supplier_name ilike @search or client_name ilike @search or subject ilike @search)";
        var ids = new List<Guid>(); await using (var q = c.CreateCommand()) { q.CommandText = $"select id from public.purchase_orders where {where} order by order_date desc,created_at desc limit @limit offset @offset"; ListParams(q, search, status, archivedOnly, page, pageSize); await using var r = await q.ExecuteReaderAsync(token); while (await r.ReadAsync(token)) ids.Add(r.GetGuid(0)); }
        var items = new List<PurchaseOrderDto>(); foreach (var id in ids) items.Add(await Required(c, null, id, token)); await using var count = c.CreateCommand(); count.CommandText = $"select count(*) from public.purchase_orders where {where}"; ListParams(count, search, status, archivedOnly, page, pageSize); return new(items, page, pageSize, (long)(await count.ExecuteScalarAsync(token) ?? 0L));
    }
    public async Task<PurchaseOrderDto?> GetAsync(Guid id, CancellationToken token) { await using var c = await dataSource.OpenConnectionAsync(token); return await Read(c, null, id, token); }
    public Task<PurchaseOrderDto> CreateAsync(SavePurchaseOrderRequest r, string number, CurrentUser actor, CancellationToken token) => Execute(async (c, t) =>
    {
        var supplier = await Supplier(c, t, r, token); var client = await Client(c, t, r, token); var quotation = await Quotation(c, t, r, client.Id, token); var lines = await Lines(c, t, r.Lines, supplier.Id, token); var totals = Calculate(lines, r.Charges, r.VatEnabled); var doc = IsSend(r) ? "Sent" : "Draft"; var id = Guid.NewGuid();
        await using var q = c.CreateCommand(); q.Transaction = t; q.CommandText = "insert into public.purchase_orders(id,po_number,order_date,client_id,client_name,supplier_id,supplier_name,contact_person,subject,quotation_id,quotation_number,payment_method,payment_term,delivery_location,delivery_mode,notes,terms,subtotal_amount,vat_enabled,vat_rate,vat_amount,total_amount,status,document_status,delivery_status,payment_status,sent_at,sent_by,created_by,updated_by) values(@id,@num,@date,@cid,@cname,@sid,@sname,@contact,@subject,@qid,@qnum,@method,@term,@location,@mode,@notes,@terms,@subtotal,@vaton,@rate,@vat,@total,@status,@doc,'Pending','Not Due',case when @doc='Sent' then now() end,case when @doc='Sent' then @actor end,@actor,@actor)"; Header(q,id,number,r,supplier,client,quotation,totals,doc,actor.Id); await q.ExecuteNonQueryAsync(token); await Children(c,t,id,lines,r.Charges,token); await Audit(c,t,id,"Created",number,$"Purchase order created for {supplier.Name}.",Legacy(doc,"Pending","Not Due"),totals.Total,actor,token); return await Required(c,t,id,token);
    }, token);
    public Task<PurchaseOrderDto> UpdateAsync(Guid id, SavePurchaseOrderRequest r, CurrentUser actor, CancellationToken token) => Execute(async (c,t) =>
    {
        var old=await Required(c,t,id,token); if(old.DocumentStatus=="Cancelled") throw new ResourceConflictException("Cancelled purchase orders cannot be edited."); var supplier=await Supplier(c,t,r,token); var client=await Client(c,t,r,token); var quotation=await Quotation(c,t,r,client.Id,token); var lines=await Lines(c,t,r.Lines,supplier.Id,token); var totals=Calculate(lines,r.Charges,r.VatEnabled); var doc=IsSend(r)?"Sent":old.DocumentStatus; var status=Legacy(doc,old.DeliveryStatus,old.PaymentStatus);
        await using var q=c.CreateCommand();q.Transaction=t;q.CommandText="update public.purchase_orders set order_date=@date,client_id=@cid,client_name=@cname,supplier_id=@sid,supplier_name=@sname,contact_person=@contact,subject=@subject,quotation_id=@qid,quotation_number=@qnum,payment_method=@method,payment_term=@term,delivery_location=@location,delivery_mode=@mode,notes=@notes,terms=@terms,subtotal_amount=@subtotal,vat_enabled=@vaton,vat_rate=@rate,vat_amount=@vat,total_amount=@total,status=@status,document_status=@doc,sent_at=case when @doc='Sent' then coalesce(sent_at,now()) end,sent_by=case when @doc='Sent' then @actor else sent_by end,updated_by=@actor where id=@id and archived_at is null and deleted_at is null and version=@version returning id";Header(q,id,old.PoNumber,r,supplier,client,quotation,totals,doc,actor.Id);q.Parameters.AddWithValue("version",r.Version!.Value);if(await q.ExecuteScalarAsync(token)is null)throw Stale();await Children(c,t,id,lines,r.Charges,token);await Audit(c,t,id,"Updated",old.PoNumber,"Purchase order details, lines and charges were updated.",status,totals.Total,actor,token);return await Required(c,t,id,token);
    },token);
    public Task<PurchaseOrderDto> ChangeStatusAsync(Guid id,ChangePurchaseOrderStatusRequest r,CurrentUser actor,CancellationToken token)=>Execute(async(c,t)=>
    {
        var old=await Required(c,t,id,token); var doc=r.DocumentStatus?.Trim()??old.DocumentStatus;var delivery=r.DeliveryStatus?.Trim()??old.DeliveryStatus;var payment=r.PaymentStatus?.Trim()??old.PaymentStatus; ValidateStatuses(old,doc,delivery,payment,r.Reason);var status=Legacy(doc,delivery,payment);
        await using var q=c.CreateCommand();q.Transaction=t;q.CommandText="update public.purchase_orders set document_status=@doc,delivery_status=@delivery,payment_status=@payment,status=@status,sent_at=case when @doc='Sent' then coalesce(sent_at,now()) else sent_at end,sent_by=case when @doc='Sent' then coalesce(sent_by,@actor) else sent_by end,voided_at=case when @doc='Cancelled' then now() else voided_at end,voided_by=case when @doc='Cancelled' then @actor else voided_by end,void_reason=case when @doc='Cancelled' then @reason else void_reason end,updated_by=@actor where id=@id and archived_at is null and deleted_at is null and version=@version returning id";q.Parameters.AddWithValue("id",id);q.Parameters.AddWithValue("doc",doc);q.Parameters.AddWithValue("delivery",delivery);q.Parameters.AddWithValue("payment",payment);q.Parameters.AddWithValue("status",status);q.Parameters.AddWithValue("reason",(object?)r.Reason?.Trim()??DBNull.Value);q.Parameters.AddWithValue("actor",actor.Id);q.Parameters.AddWithValue("version",r.Version);if(await q.ExecuteScalarAsync(token)is null)throw Stale();await Audit(c,t,id,doc=="Cancelled"?"Voided":"Status changed",old.PoNumber,doc=="Cancelled"?$"Purchase order voided: {r.Reason?.Trim()}":"Purchase order lifecycle status was updated.",status,old.TotalAmount,actor,token);var result=await Required(c,t,id,token);if(r.ArchiveAfterVoiding){var archive=new ChangePurchaseOrderArchiveRequest(result.Version);return await SetArchivedIn(c,t,result,archive,true,actor,token);}return result;
    },token);
    public Task<PurchaseOrderDto> SetArchivedAsync(Guid id,ChangePurchaseOrderArchiveRequest r,bool archive,CurrentUser actor,CancellationToken token)=>Execute(async(c,t)=>{var old=await Required(c,t,id,token);return await SetArchivedIn(c,t,old,r,archive,actor,token);},token);
    private static async Task<PurchaseOrderDto> SetArchivedIn(NpgsqlConnection c,NpgsqlTransaction? t,PurchaseOrderDto old,ChangePurchaseOrderArchiveRequest r,bool archive,CurrentUser actor,CancellationToken token){if(r.Version<=0)throw new RequestValidationException("The current purchase order version is required.");await using var q=c.CreateCommand();q.Transaction=t;q.CommandText=archive?"update public.purchase_orders set archived_at=now(),archived_by=@actor,updated_by=@actor where id=@id and archived_at is null and deleted_at is null and version=@version returning id":"update public.purchase_orders set archived_at=null,archived_by=null,updated_by=@actor where id=@id and archived_at is not null and deleted_at is null and version=@version returning id";q.Parameters.AddWithValue("id",old.Id);q.Parameters.AddWithValue("actor",actor.Id);q.Parameters.AddWithValue("version",r.Version);if(await q.ExecuteScalarAsync(token)is null)throw Stale();await Audit(c,t,old.Id,archive?"Archived":"Restored",old.PoNumber,archive?"Purchase order was archived with relationships retained.":"Purchase order was restored.",old.Status,old.TotalAmount,actor,token);return await Required(c,t,old.Id,token);}
    private static async Task<PurchaseOrderDto?> Read(NpgsqlConnection c,NpgsqlTransaction? t,Guid id,CancellationToken token){HeaderRow h;await using(var q=c.CreateCommand()){q.Transaction=t;q.CommandText="select id,po_number,order_date,client_id,client_name,supplier_id,supplier_name,contact_person,subject,quotation_id,quotation_number,payment_method,payment_term,delivery_location,delivery_mode,notes,terms,subtotal_amount,vat_enabled,vat_rate,vat_amount,total_amount,status,document_status,delivery_status,payment_status,void_reason,created_at,updated_at,archived_at,version from public.purchase_orders where id=@id and deleted_at is null";q.Parameters.AddWithValue("id",id);await using var r=await q.ExecuteReaderAsync(token);if(!await r.ReadAsync(token))return null;h=new(r.GetGuid(0),r.GetString(1),r.GetFieldValue<DateOnly>(2),r.IsDBNull(3)?null:r.GetGuid(3),r.GetString(4),r.IsDBNull(5)?null:r.GetGuid(5),r.GetString(6),r.GetString(7),r.GetString(8),r.IsDBNull(9)?null:r.GetGuid(9),r.GetString(10),r.GetString(11),r.GetString(12),r.GetString(13),r.GetString(14),r.GetString(15),r.GetString(16),r.GetDecimal(17),r.GetBoolean(18),r.GetDecimal(19),r.GetDecimal(20),r.GetDecimal(21),r.GetString(22),r.GetString(23),r.GetString(24),r.GetString(25),r.IsDBNull(26)?null:r.GetString(26),r.GetFieldValue<DateTimeOffset>(27),r.GetFieldValue<DateTimeOffset>(28),r.IsDBNull(29)?null:r.GetFieldValue<DateTimeOffset>(29),r.GetInt64(30));}var lines=new List<PurchaseOrderLineDto>();await using(var q=c.CreateCommand()){q.Transaction=t;q.CommandText="select id,item_id,variant_id,photo_url,item_name,variant_label,product_code,unit_of_measure,quantity,unit_cost,line_amount from public.purchase_order_lines where purchase_order_id=@id order by position";q.Parameters.AddWithValue("id",id);await using var r=await q.ExecuteReaderAsync(token);while(await r.ReadAsync(token))lines.Add(new(r.GetGuid(0),r.IsDBNull(1)?null:r.GetGuid(1),r.IsDBNull(2)?null:r.GetGuid(2),r.IsDBNull(3)?string.Empty:r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),r.GetDecimal(8),r.GetDecimal(9),r.GetDecimal(10)));}var charges=new List<PurchaseOrderChargeDto>();await using(var q=c.CreateCommand()){q.Transaction=t;q.CommandText="select id,label,amount,position from public.purchase_order_charges where purchase_order_id=@id order by position";q.Parameters.AddWithValue("id",id);await using var r=await q.ExecuteReaderAsync(token);while(await r.ReadAsync(token))charges.Add(new(r.GetGuid(0),r.GetString(1),r.GetDecimal(2),r.GetInt32(3)));}return new(h.Id,h.Number,h.Date,h.ClientId,h.ClientName,h.SupplierId,h.SupplierName,h.Contact,h.Subject,h.QuotationId,h.QuotationNumber,h.Method,h.Term,h.Location,h.Mode,h.Notes,h.Terms,h.Subtotal,h.VatEnabled,h.Rate,h.Vat,h.Total,h.Status,h.Document,h.Delivery,h.Payment,h.VoidReason,lines,charges,h.Created,h.Updated,h.Archived,h.Version);}
    private static async Task<PurchaseOrderDto> Required(NpgsqlConnection c,NpgsqlTransaction? t,Guid id,CancellationToken token)=>await Read(c,t,id,token)??throw new ResourceNotFoundException($"Purchase order '{id}' was not found.");
    private static async Task<SupplierRow> Supplier(NpgsqlConnection c,NpgsqlTransaction? t,SavePurchaseOrderRequest r,CancellationToken token){if(r.SupplierId is null)throw new RequestValidationException("Choose an active Supplier.");await using var q=c.CreateCommand();q.Transaction=t;q.CommandText="select id,name from public.suppliers where id=@id and archived_at is null and deleted_at is null";q.Parameters.AddWithValue("id",r.SupplierId.Value);await using var x=await q.ExecuteReaderAsync(token);if(!await x.ReadAsync(token))throw new RequestValidationException("Choose an active Supplier.");return new(x.GetGuid(0),x.GetString(1));}
    private static async Task<ClientRow> Client(NpgsqlConnection c,NpgsqlTransaction? t,SavePurchaseOrderRequest r,CancellationToken token){if(r.ClientId is null)throw new RequestValidationException("Choose an active Client.");await using var q=c.CreateCommand();q.Transaction=t;q.CommandText="select id,name from public.clients where id=@id and archived_at is null and deleted_at is null";q.Parameters.AddWithValue("id",r.ClientId.Value);await using var x=await q.ExecuteReaderAsync(token);if(!await x.ReadAsync(token))throw new RequestValidationException("Choose an active Client.");return new(x.GetGuid(0),x.GetString(1));}
    private static async Task<QuotationRow> Quotation(NpgsqlConnection c,NpgsqlTransaction? t,SavePurchaseOrderRequest r,Guid clientId,CancellationToken token){if(r.QuotationId is null)return new(null,string.Empty);await using var q=c.CreateCommand();q.Transaction=t;q.CommandText="select id,quotation_number from public.quotations where id=@id and client_id=@client and status='Approved' and archived_at is null and deleted_at is null";q.Parameters.AddWithValue("id",r.QuotationId.Value);q.Parameters.AddWithValue("client",clientId);await using var x=await q.ExecuteReaderAsync(token);if(!await x.ReadAsync(token))throw new RequestValidationException("Choose an approved quotation for the selected Client.");return new(x.GetGuid(0),x.GetString(1));}
    private static async Task<IReadOnlyList<LineRow>> Lines(NpgsqlConnection c,NpgsqlTransaction? t,IReadOnlyList<SavePurchaseOrderLineRequest> rows,Guid supplierId,CancellationToken token){var result=new List<LineRow>();foreach(var r in rows){if(r.ItemId is null){result.Add(new(Guid.NewGuid(),null,null,r.Photo?.Trim(),r.ItemName.Trim(),r.VariantLabel?.Trim()??string.Empty,r.ProductCode?.Trim()??string.Empty,r.UnitOfMeasure.Trim(),r.Quantity,r.UnitCost));continue;}await using var q=c.CreateCommand();q.Transaction=t;q.CommandText="select item.name,item.photo_url,item.product_code,item.unit_of_measure,item.raw_cost,item.supplier_id,variant.id,variant.name,variant.value,variant.photo_url,variant.product_code,variant.unit_of_measure,variant.raw_cost from public.items item left join public.item_variants variant on variant.item_id=item.id and variant.id=@variant where item.id=@item and item.archived_at is null and item.deleted_at is null";q.Parameters.AddWithValue("item",r.ItemId.Value);q.Parameters.AddWithValue("variant",(object?)r.VariantId??DBNull.Value);await using var x=await q.ExecuteReaderAsync(token);if(!await x.ReadAsync(token)||x.IsDBNull(5)||x.GetGuid(5)!=supplierId)throw new RequestValidationException("A selected Item is unavailable for this Supplier.");var has=!x.IsDBNull(6);if(r.VariantId is not null&&!has)throw new RequestValidationException("A selected Item variant is unavailable.");result.Add(new(Guid.NewGuid(),r.ItemId,has?x.GetGuid(6):null,has&&!x.IsDBNull(9)?x.GetString(9):x.IsDBNull(1)?null:x.GetString(1),x.GetString(0),has?$"{x.GetString(7)}: {x.GetString(8)}":string.Empty,has&&!x.IsDBNull(10)?x.GetString(10):x.IsDBNull(2)?string.Empty:x.GetString(2),has?x.GetString(11):x.GetString(3),r.Quantity,has?x.GetDecimal(12):x.GetDecimal(4)));}return result;}
    private static Totals Calculate(IReadOnlyList<LineRow> l,IReadOnlyList<SavePurchaseOrderChargeRequest> c,bool vat){var sub=l.Sum(x=>decimal.Round(x.Qty*x.Cost,2));var v=vat?decimal.Round(sub*VatRate,2):0;return new(sub,v,sub+v+c.Sum(x=>x.Amount));}
    private static async Task Children(NpgsqlConnection c,NpgsqlTransaction? t,Guid id,IReadOnlyList<LineRow> lines,IReadOnlyList<SavePurchaseOrderChargeRequest> charges,CancellationToken token){foreach(var table in new[]{"purchase_order_lines","purchase_order_charges"}){await using var d=c.CreateCommand();d.Transaction=t;d.CommandText=$"delete from public.{table} where purchase_order_id=@id";d.Parameters.AddWithValue("id",id);await d.ExecuteNonQueryAsync(token);}for(var i=0;i<lines.Count;i++){var l=lines[i];await using var q=c.CreateCommand();q.Transaction=t;q.CommandText="insert into public.purchase_order_lines(id,purchase_order_id,item_id,variant_id,position,photo_url,item_name,variant_label,product_code,unit_of_measure,quantity,unit_cost) values(@lid,@id,@item,@variant,@pos,@photo,@name,@label,@code,@unit,@qty,@cost)";q.Parameters.AddWithValue("lid",l.Id);q.Parameters.AddWithValue("id",id);q.Parameters.AddWithValue("item",(object?)l.ItemId??DBNull.Value);q.Parameters.AddWithValue("variant",(object?)l.VariantId??DBNull.Value);q.Parameters.AddWithValue("pos",i+1);q.Parameters.AddWithValue("photo",(object?)l.Photo??DBNull.Value);q.Parameters.AddWithValue("name",l.Name);q.Parameters.AddWithValue("label",l.Label);q.Parameters.AddWithValue("code",l.Code);q.Parameters.AddWithValue("unit",l.Unit);q.Parameters.AddWithValue("qty",l.Qty);q.Parameters.AddWithValue("cost",l.Cost);await q.ExecuteNonQueryAsync(token);}for(var i=0;i<charges.Count;i++){await using var q=c.CreateCommand();q.Transaction=t;q.CommandText="insert into public.purchase_order_charges(purchase_order_id,label,amount,position) values(@id,@label,@amount,@pos)";q.Parameters.AddWithValue("id",id);q.Parameters.AddWithValue("label",charges[i].Label.Trim());q.Parameters.AddWithValue("amount",charges[i].Amount);q.Parameters.AddWithValue("pos",i+1);await q.ExecuteNonQueryAsync(token);}}
    private static void Header(NpgsqlCommand q,Guid id,string number,SavePurchaseOrderRequest r,SupplierRow s,ClientRow c,QuotationRow quote,Totals total,string doc,Guid actor){q.Parameters.AddWithValue("id",id);q.Parameters.AddWithValue("num",number);q.Parameters.AddWithValue("date",r.OrderDate);q.Parameters.AddWithValue("cid",c.Id);q.Parameters.AddWithValue("cname",c.Name);q.Parameters.AddWithValue("sid",s.Id);q.Parameters.AddWithValue("sname",s.Name);q.Parameters.AddWithValue("contact",r.ContactPerson?.Trim()??string.Empty);q.Parameters.AddWithValue("subject",r.Subject?.Trim()??string.Empty);q.Parameters.AddWithValue("qid",(object?)quote.Id??DBNull.Value);q.Parameters.AddWithValue("qnum",quote.Number);q.Parameters.AddWithValue("method",r.PaymentMethod?.Trim()??string.Empty);q.Parameters.AddWithValue("term",r.PaymentTerm?.Trim()??string.Empty);q.Parameters.AddWithValue("location",r.DeliveryLocation?.Trim()??string.Empty);q.Parameters.AddWithValue("mode",r.DeliveryMode?.Trim()??string.Empty);q.Parameters.AddWithValue("notes",r.Notes?.Trim()??string.Empty);q.Parameters.AddWithValue("terms",r.Terms?.Trim()??string.Empty);q.Parameters.AddWithValue("subtotal",total.Subtotal);q.Parameters.AddWithValue("vaton",r.VatEnabled);q.Parameters.AddWithValue("rate",VatRate);q.Parameters.AddWithValue("vat",total.Vat);q.Parameters.AddWithValue("total",total.Total);q.Parameters.AddWithValue("doc",doc);q.Parameters.AddWithValue("status",Legacy(doc,"Pending","Not Due"));q.Parameters.AddWithValue("actor",actor);}
    private static void ListParams(NpgsqlCommand q,string search,string? status,bool archived,int page,int size){q.Parameters.AddWithValue("archived",archived);q.Parameters.AddWithValue("status",status??string.Empty);q.Parameters.AddWithValue("search",string.IsNullOrWhiteSpace(search)?string.Empty:$"%{search}%");q.Parameters.AddWithValue("limit",size);q.Parameters.AddWithValue("offset",(page-1)*size);}
    private static async Task Audit(NpgsqlConnection c,NpgsqlTransaction? t,Guid id,string action,string entity,string description,string status,decimal amount,CurrentUser actor,CancellationToken token){await using var q=c.CreateCommand();q.Transaction=t;q.CommandText="insert into public.audit_records(record_id,module,action,entity,description,actor_id,actor_name,tone,amount,status) values(@id,'Purchase Orders',@action,@entity,@description,@actor,@name,@tone,@amount,@status)";q.Parameters.AddWithValue("id",id);q.Parameters.AddWithValue("action",action);q.Parameters.AddWithValue("entity",entity);q.Parameters.AddWithValue("description",description);q.Parameters.AddWithValue("actor",actor.Id);q.Parameters.AddWithValue("name",actor.Username);q.Parameters.AddWithValue("tone",action is "Created"?"success":action is "Voided"?"danger":"info");q.Parameters.AddWithValue("amount",amount);q.Parameters.AddWithValue("status",status);await q.ExecuteNonQueryAsync(token);}
    private async Task<T> Execute<T>(Func<NpgsqlConnection,NpgsqlTransaction?,Task<T>> action,CancellationToken token){await using var c=await dataSource.OpenConnectionAsync(token);await using var t=Transaction.Current is null?await c.BeginTransactionAsync(token):null;var value=await action(c,t);if(t is not null)await t.CommitAsync(token);return value;}
    private static bool IsSend(SavePurchaseOrderRequest r)=>string.Equals(r.Intent,"send",StringComparison.OrdinalIgnoreCase);
    private static string Legacy(string doc,string delivery,string payment)=>doc=="Cancelled"?"Cancelled":doc=="Draft"?"Not yet sent":payment is "To Pay" or "Overdue"?"For Payment":delivery=="Delivered"?"Delivered":delivery is "Pending" or "Partially Delivered"?"Waiting for Delivery":"Sent";
    private static void ValidateStatuses(PurchaseOrderDto old,string doc,string delivery,string payment,string? reason){if(doc is not ("Draft" or "Sent" or "Cancelled")||delivery is not ("Pending" or "Partially Delivered" or "Delivered")||payment is not ("Not Due" or "To Pay" or "Overdue" or "Paid"))throw new RequestValidationException("Purchase order statuses are invalid.");if(old.DocumentStatus=="Cancelled")throw new ResourceConflictException("Cancelled purchase orders cannot change status.");if(doc=="Draft"&&old.DocumentStatus=="Sent")throw new ResourceConflictException("A sent purchase order cannot return to draft.");if(doc=="Cancelled"&&string.IsNullOrWhiteSpace(reason))throw new RequestValidationException("A void reason is required.");}
    private static ConcurrencyConflictException Stale()=>new("This purchase order changed after you opened it. Reload and try again.");
    private sealed record HeaderRow(Guid Id,string Number,DateOnly Date,Guid? ClientId,string ClientName,Guid? SupplierId,string SupplierName,string Contact,string Subject,Guid? QuotationId,string QuotationNumber,string Method,string Term,string Location,string Mode,string Notes,string Terms,decimal Subtotal,bool VatEnabled,decimal Rate,decimal Vat,decimal Total,string Status,string Document,string Delivery,string Payment,string? VoidReason,DateTimeOffset Created,DateTimeOffset Updated,DateTimeOffset? Archived,long Version);
    private sealed record SupplierRow(Guid Id,string Name); private sealed record ClientRow(Guid Id,string Name); private sealed record QuotationRow(Guid? Id,string Number); private sealed record LineRow(Guid Id,Guid? ItemId,Guid? VariantId,string? Photo,string Name,string Label,string Code,string Unit,decimal Qty,decimal Cost); private sealed record Totals(decimal Subtotal,decimal Vat,decimal Total);
}
