using System.Transactions;
using AdielSystem.Application.Common;
using AdielSystem.Application.Quotations;
using AdielSystem.Application.Security;
using Npgsql;

namespace AdielSystem.Infrastructure.Quotations;

public sealed class QuotationRepository(NpgsqlDataSource dataSource) : IQuotationRepository
{
    private const decimal VatRate = 0.12m;

    public async Task<QuotationPageDto> ListAsync(string search, string? status, bool archivedOnly, int page, int pageSize, CancellationToken token)
    {
        await using var connection = await dataSource.OpenConnectionAsync(token);
        const string where = "deleted_at is null and (@archived_only = (archived_at is not null)) and (@status='' or status=@status) and (@search='' or quotation_number ilike @search or client_name ilike @search or subject ilike @search or project_location ilike @search)";
        var ids = new List<Guid>();
        await using (var command = connection.CreateCommand())
        {
            command.CommandText = $"select id from public.quotations where {where} order by quotation_date desc,created_at desc limit @limit offset @offset";
            AddListParameters(command, search, status, archivedOnly, page, pageSize);
            await using var reader = await command.ExecuteReaderAsync(token);
            while (await reader.ReadAsync(token)) ids.Add(reader.GetGuid(0));
        }
        var items = new List<QuotationDto>();
        foreach (var id in ids) items.Add(await RequiredAsync(connection, null, id, token));
        await using var count = connection.CreateCommand(); count.CommandText = $"select count(*) from public.quotations where {where}"; AddListParameters(count, search, status, archivedOnly, page, pageSize);
        return new(items, page, pageSize, (long)(await count.ExecuteScalarAsync(token) ?? 0L));
    }

    public async Task<QuotationDto?> GetAsync(Guid id, CancellationToken token) { await using var connection = await dataSource.OpenConnectionAsync(token); return await ReadAsync(connection, null, id, token); }

    public Task<QuotationDto> CreateAsync(SaveQuotationRequest request, string quotationNumber, CurrentUser actor, CancellationToken token) => ExecuteAsync(async (connection, transaction) =>
    {
        var client = await ResolveClientAsync(connection, transaction, request, token);
        var lines = await ResolveLinesAsync(connection, transaction, request.Lines, token);
        var totals = Calculate(lines, request.Charges, request.VatEnabled);
        var id = Guid.NewGuid(); var status = IsSubmit(request) ? "For Approval" : "Draft";
        await using (var command = connection.CreateCommand()) { command.Transaction = transaction; command.CommandText = "insert into public.quotations (id,quotation_number,quotation_date,client_id,client_name,contact_id,contact_person,subject,project_location,lead_time,notes,terms,subtotal_amount,vat_enabled,vat_rate,vat_amount,total_amount,estimated_profit,status,submitted_at,submitted_by,created_by,updated_by) values (@id,@number,@date,@client_id,@client_name,@contact_id,@contact_person,@subject,@location,@lead_time,@notes,@terms,@subtotal,@vat_enabled,@vat_rate,@vat,@total,@profit,@status,case when @status='For Approval' then now() end,case when @status='For Approval' then @actor end,@actor,@actor)"; AddHeader(command, id, quotationNumber, request, client, totals, status, actor.Id); await command.ExecuteNonQueryAsync(token); }
        await ReplaceChildrenAsync(connection, transaction, id, lines, request.Charges, token);
        await AuditAsync(connection, transaction, id, "Created", quotationNumber, $"Quotation created for {client.Name}.", status, totals.Total, actor, token);
        return await RequiredAsync(connection, transaction, id, token);
    }, token);

    public Task<QuotationDto> UpdateAsync(Guid id, SaveQuotationRequest request, CurrentUser actor, CancellationToken token) => ExecuteAsync(async (connection, transaction) =>
    {
        var existing = await RequiredAsync(connection, transaction, id, token);
        if (existing.Status is "Approved" or "Voided") throw new ResourceConflictException("Approved or voided quotations cannot be edited.");
        var client = await ResolveClientAsync(connection, transaction, request, token);
        var lines = await ResolveLinesAsync(connection, transaction, request.Lines, token); var totals = Calculate(lines, request.Charges, request.VatEnabled); var status = IsSubmit(request) ? "For Approval" : "Draft";
        await using (var command = connection.CreateCommand()) { command.Transaction = transaction; command.CommandText = "update public.quotations set quotation_date=@date,client_id=@client_id,client_name=@client_name,contact_id=@contact_id,contact_person=@contact_person,subject=@subject,project_location=@location,lead_time=@lead_time,notes=@notes,terms=@terms,subtotal_amount=@subtotal,vat_enabled=@vat_enabled,vat_rate=@vat_rate,vat_amount=@vat,total_amount=@total,estimated_profit=@profit,status=@status,submitted_at=case when @status='For Approval' then coalesce(submitted_at,now()) end,submitted_by=case when @status='For Approval' then @actor end,rejection_reason=null,rejected_at=null,rejected_by=null,updated_by=@actor where id=@id and archived_at is null and deleted_at is null and version=@version returning id"; AddHeader(command, id, existing.QuotationNumber, request, client, totals, status, actor.Id); command.Parameters.AddWithValue("version", request.Version!.Value); if (await command.ExecuteScalarAsync(token) is null) throw Stale(); }
        await ReplaceChildrenAsync(connection, transaction, id, lines, request.Charges, token);
        await AuditAsync(connection, transaction, id, "Updated", existing.QuotationNumber, "Quotation details, lines and charges were updated.", status, totals.Total, actor, token);
        return await RequiredAsync(connection, transaction, id, token);
    }, token);

    public Task<QuotationDto> ChangeStatusAsync(Guid id, ChangeQuotationStatusRequest request, CurrentUser actor, CancellationToken token) => ExecuteAsync(async (connection, transaction) =>
    {
        var existing = await RequiredAsync(connection, transaction, id, token); var target = request.Status.Trim(); ValidateTransition(existing.Status, target, request.Reason);
        await using var command = connection.CreateCommand(); command.Transaction = transaction;
        command.CommandText = "update public.quotations set status=@status,submitted_at=case when @status='For Approval' then now() else submitted_at end,submitted_by=case when @status='For Approval' then @actor else submitted_by end,approved_at=case when @status='Approved' then now() end,approved_by=case when @status='Approved' then @actor end,rejected_at=case when @status='Rejected' then now() end,rejected_by=case when @status='Rejected' then @actor end,rejection_reason=case when @status='Rejected' then @reason end,voided_at=case when @status='Voided' then now() end,voided_by=case when @status='Voided' then @actor end,void_reason=case when @status='Voided' then @reason end,archived_at=case when @archive_after then now() else archived_at end,archived_by=case when @archive_after then @actor else archived_by end,updated_by=@actor where id=@id and archived_at is null and deleted_at is null and version=@version returning id";
        command.Parameters.AddWithValue("status", target); command.Parameters.AddWithValue("reason", request.Reason?.Trim() ?? string.Empty); command.Parameters.AddWithValue("archive_after", target == "Voided" && request.ArchiveAfterVoiding); command.Parameters.AddWithValue("actor", actor.Id); command.Parameters.AddWithValue("id", id); command.Parameters.AddWithValue("version", request.Version); if (await command.ExecuteScalarAsync(token) is null) throw Stale();
        await AuditAsync(connection, transaction, id, target == "Voided" ? "Voided" : "Status changed", existing.QuotationNumber, target == "Voided" ? $"Quotation voided: {request.Reason?.Trim()}" : $"Quotation status changed from {existing.Status} to {target}.", target, existing.TotalAmount, actor, token);
        return await RequiredAsync(connection, transaction, id, token);
    }, token);

    public Task<QuotationDto> SetArchivedAsync(Guid id, ChangeQuotationArchiveRequest request, bool archived, CurrentUser actor, CancellationToken token) => ExecuteAsync(async (connection, transaction) =>
    {
        if (request.Version <= 0) throw new RequestValidationException("The current quotation version is required."); var existing = await RequiredAsync(connection, transaction, id, token);
        await using var command = connection.CreateCommand(); command.Transaction = transaction; command.CommandText = archived ? "update public.quotations set archived_at=now(),archived_by=@actor,updated_by=@actor where id=@id and archived_at is null and deleted_at is null and version=@version returning id" : "update public.quotations set archived_at=null,archived_by=null,updated_by=@actor where id=@id and archived_at is not null and deleted_at is null and version=@version returning id"; command.Parameters.AddWithValue("actor", actor.Id); command.Parameters.AddWithValue("id", id); command.Parameters.AddWithValue("version", request.Version); if (await command.ExecuteScalarAsync(token) is null) throw Stale(); await AuditAsync(connection, transaction, id, archived ? "Archived" : "Restored", existing.QuotationNumber, archived ? "Quotation was archived with relationships retained." : "Quotation was restored.", existing.Status, existing.TotalAmount, actor, token); return await RequiredAsync(connection, transaction, id, token);
    }, token);

    private static async Task<QuotationDto?> ReadAsync(NpgsqlConnection connection, NpgsqlTransaction? transaction, Guid id, CancellationToken token)
    {
        Header h; await using (var command = connection.CreateCommand()) { command.Transaction = transaction; command.CommandText = "select id,quotation_number,quotation_date,client_id,client_name,contact_id,contact_person,subject,project_location,lead_time,notes,terms,subtotal_amount,vat_enabled,vat_rate,vat_amount,total_amount,estimated_profit,status,rejection_reason,void_reason,created_at,updated_at,archived_at,version from public.quotations where id=@id and deleted_at is null"; command.Parameters.AddWithValue("id", id); await using var reader = await command.ExecuteReaderAsync(token); if (!await reader.ReadAsync(token)) return null; h = new(reader.GetGuid(0),reader.GetString(1),reader.GetFieldValue<DateOnly>(2),reader.IsDBNull(3)?null:reader.GetGuid(3),reader.GetString(4),reader.IsDBNull(5)?null:reader.GetGuid(5),reader.GetString(6),reader.GetString(7),reader.GetString(8),reader.GetString(9),reader.GetString(10),reader.GetString(11),reader.GetDecimal(12),reader.GetBoolean(13),reader.GetDecimal(14),reader.GetDecimal(15),reader.GetDecimal(16),reader.GetDecimal(17),reader.GetString(18),reader.IsDBNull(19)?null:reader.GetString(19),reader.IsDBNull(20)?null:reader.GetString(20),reader.GetFieldValue<DateTimeOffset>(21),reader.GetFieldValue<DateTimeOffset>(22),reader.IsDBNull(23)?null:reader.GetFieldValue<DateTimeOffset>(23),reader.GetInt64(24)); }
        var lines = new List<QuotationLineDto>(); await using (var command = connection.CreateCommand()) { command.Transaction=transaction; command.CommandText="select id,item_id,variant_id,photo_url,item_name,variant_label,product_code,unit_of_measure,quantity,unit_price,unit_cost,line_amount from public.quotation_lines where quotation_id=@id order by position"; command.Parameters.AddWithValue("id",id); await using var reader=await command.ExecuteReaderAsync(token); while(await reader.ReadAsync(token)) lines.Add(new(reader.GetGuid(0),reader.IsDBNull(1)?null:reader.GetGuid(1),reader.IsDBNull(2)?null:reader.GetGuid(2),reader.IsDBNull(3)?string.Empty:reader.GetString(3),reader.GetString(4),reader.GetString(5),reader.GetString(6),reader.GetString(7),reader.GetDecimal(8),reader.GetDecimal(9),reader.GetDecimal(10),reader.GetDecimal(11))); }
        var charges = new List<QuotationChargeDto>(); await using (var command=connection.CreateCommand()) { command.Transaction=transaction; command.CommandText="select id,label,amount,position from public.quotation_charges where quotation_id=@id order by position"; command.Parameters.AddWithValue("id",id); await using var reader=await command.ExecuteReaderAsync(token); while(await reader.ReadAsync(token)) charges.Add(new(reader.GetGuid(0),reader.GetString(1),reader.GetDecimal(2),reader.GetInt32(3))); }
        return new(h.Id,h.Number,h.Date,h.ClientId,h.ClientName,h.ContactId,h.ContactPerson,h.Subject,h.Location,h.LeadTime,h.Notes,h.Terms,h.Subtotal,h.VatEnabled,h.VatRate,h.Vat,h.Total,h.Profit,h.Status,h.RejectionReason,h.VoidReason,lines,charges,h.CreatedAt,h.UpdatedAt,h.ArchivedAt,h.Version);
    }
    private static async Task<QuotationDto> RequiredAsync(NpgsqlConnection c,NpgsqlTransaction? t,Guid id,CancellationToken token)=>await ReadAsync(c,t,id,token)??throw new ResourceNotFoundException($"Quotation '{id}' was not found.");
    private static async Task<ClientSnapshot> ResolveClientAsync(NpgsqlConnection c,NpgsqlTransaction? t,SaveQuotationRequest r,CancellationToken token) { if(r.ClientId is null) return new(null,r.ClientName.Trim(),null,r.ContactPerson.Trim()); await using var command=c.CreateCommand(); command.Transaction=t; command.CommandText="select client.id,client.name,contact.id,contact.name from public.clients client left join public.client_contacts contact on contact.client_id=client.id and contact.id=@contact_id where client.id=@client_id and client.deleted_at is null and client.archived_at is null"; command.Parameters.AddWithValue("client_id",r.ClientId.Value); command.Parameters.AddWithValue("contact_id",(object?)r.ContactId??DBNull.Value); await using var reader=await command.ExecuteReaderAsync(token); if(!await reader.ReadAsync(token)) throw new RequestValidationException("Choose an active Client and contact."); if(IsSubmit(r)&&reader.IsDBNull(2)) throw new RequestValidationException("Choose a contact belonging to the selected Client."); return new(reader.GetGuid(0),reader.GetString(1),reader.IsDBNull(2)?null:reader.GetGuid(2),reader.IsDBNull(3)?string.Empty:reader.GetString(3)); }
    private static async Task<IReadOnlyList<ResolvedLine>> ResolveLinesAsync(NpgsqlConnection c,NpgsqlTransaction? t,IReadOnlyList<SaveQuotationLineRequest> requests,CancellationToken token) { var result=new List<ResolvedLine>(); foreach(var r in requests) { if(r.ItemId is null){result.Add(new(Guid.NewGuid(),null,null,r.Photo?.Trim(),r.ItemName.Trim(),r.VariantLabel?.Trim()??string.Empty,r.ProductCode?.Trim()??string.Empty,r.UnitOfMeasure.Trim(),r.Quantity,r.UnitPrice,r.UnitCost));continue;} await using var command=c.CreateCommand();command.Transaction=t;command.CommandText="select item.name,item.photo_url,item.product_code,item.unit_of_measure,item.raw_cost,variant.id,variant.name,variant.value,variant.photo_url,variant.product_code,variant.unit_of_measure,variant.raw_cost from public.items item left join public.item_variants variant on variant.item_id=item.id and variant.id=@variant_id where item.id=@item_id and item.deleted_at is null";command.Parameters.AddWithValue("item_id",r.ItemId.Value);command.Parameters.AddWithValue("variant_id",(object?)r.VariantId??DBNull.Value);await using var reader=await command.ExecuteReaderAsync(token);if(!await reader.ReadAsync(token)) throw new RequestValidationException("A selected Item is unavailable.");var hasVariant=!reader.IsDBNull(5);if(r.VariantId is not null&&!hasVariant) throw new RequestValidationException("A selected Item variant is unavailable.");result.Add(new(Guid.NewGuid(),r.ItemId,hasVariant?reader.GetGuid(5):null,hasVariant&&!reader.IsDBNull(8)?reader.GetString(8):reader.IsDBNull(1)?null:reader.GetString(1),reader.GetString(0),hasVariant?$"{reader.GetString(6)}: {reader.GetString(7)}":string.Empty,hasVariant&&!reader.IsDBNull(9)?reader.GetString(9):reader.IsDBNull(2)?string.Empty:reader.GetString(2),hasVariant?reader.GetString(10):reader.GetString(3),r.Quantity,r.UnitPrice,hasVariant?reader.GetDecimal(11):reader.GetDecimal(4))); } return result; }
    private static Totals Calculate(IReadOnlyList<ResolvedLine> l,IReadOnlyList<SaveQuotationChargeRequest> c,bool vat){var subtotal=l.Sum(x=>decimal.Round(x.Quantity*x.UnitPrice,2));var v=vat?decimal.Round(subtotal*VatRate,2):0;var total=subtotal+v+c.Sum(x=>x.Amount);var profit=l.Sum(x=>decimal.Round(x.Quantity*(x.UnitPrice-x.UnitCost),2));return new(subtotal,v,total,profit);}
    private static async Task ReplaceChildrenAsync(NpgsqlConnection c,NpgsqlTransaction? t,Guid id,IReadOnlyList<ResolvedLine> lines,IReadOnlyList<SaveQuotationChargeRequest> charges,CancellationToken token){foreach(var table in new[]{"quotation_lines","quotation_charges"}){await using var d=c.CreateCommand();d.Transaction=t;d.CommandText=$"delete from public.{table} where quotation_id=@id";d.Parameters.AddWithValue("id",id);await d.ExecuteNonQueryAsync(token);}for(var i=0;i<lines.Count;i++){var l=lines[i];await using var x=c.CreateCommand();x.Transaction=t;x.CommandText="insert into public.quotation_lines(id,quotation_id,item_id,variant_id,position,photo_url,item_name,variant_label,product_code,unit_of_measure,quantity,unit_price,unit_cost) values(@line_id,@id,@item_id,@variant_id,@position,@photo,@name,@variant,@code,@unit,@qty,@price,@cost)";x.Parameters.AddWithValue("line_id",l.Id);x.Parameters.AddWithValue("id",id);x.Parameters.AddWithValue("item_id",(object?)l.ItemId??DBNull.Value);x.Parameters.AddWithValue("variant_id",(object?)l.VariantId??DBNull.Value);x.Parameters.AddWithValue("position",i+1);x.Parameters.AddWithValue("photo",(object?)l.Photo??DBNull.Value);x.Parameters.AddWithValue("name",l.Name);x.Parameters.AddWithValue("variant",l.Variant);x.Parameters.AddWithValue("code",l.Code);x.Parameters.AddWithValue("unit",l.Unit);x.Parameters.AddWithValue("qty",l.Quantity);x.Parameters.AddWithValue("price",l.UnitPrice);x.Parameters.AddWithValue("cost",l.UnitCost);await x.ExecuteNonQueryAsync(token);}for(var i=0;i<charges.Count;i++){await using var x=c.CreateCommand();x.Transaction=t;x.CommandText="insert into public.quotation_charges(quotation_id,label,amount,position) values(@id,@label,@amount,@position)";x.Parameters.AddWithValue("id",id);x.Parameters.AddWithValue("label",charges[i].Label.Trim());x.Parameters.AddWithValue("amount",charges[i].Amount);x.Parameters.AddWithValue("position",i+1);await x.ExecuteNonQueryAsync(token);}}
    private static void AddHeader(NpgsqlCommand c,Guid id,string number,SaveQuotationRequest r,ClientSnapshot client,Totals totals,string status,Guid actor){c.Parameters.AddWithValue("id",id);c.Parameters.AddWithValue("number",number);c.Parameters.AddWithValue("date",r.QuotationDate);c.Parameters.AddWithValue("client_id",(object?)client.Id??DBNull.Value);c.Parameters.AddWithValue("client_name",client.Name);c.Parameters.AddWithValue("contact_id",(object?)client.ContactId??DBNull.Value);c.Parameters.AddWithValue("contact_person",client.ContactName);c.Parameters.AddWithValue("subject",r.Subject?.Trim()??string.Empty);c.Parameters.AddWithValue("location",r.ProjectLocation?.Trim()??string.Empty);c.Parameters.AddWithValue("lead_time",r.LeadTime?.Trim()??string.Empty);c.Parameters.AddWithValue("notes",r.Notes?.Trim()??string.Empty);c.Parameters.AddWithValue("terms",r.Terms?.Trim()??string.Empty);c.Parameters.AddWithValue("subtotal",totals.Subtotal);c.Parameters.AddWithValue("vat_enabled",r.VatEnabled);c.Parameters.AddWithValue("vat_rate",VatRate);c.Parameters.AddWithValue("vat",totals.Vat);c.Parameters.AddWithValue("total",totals.Total);c.Parameters.AddWithValue("profit",totals.Profit);c.Parameters.AddWithValue("status",status);c.Parameters.AddWithValue("actor",actor);}
    private static void AddListParameters(NpgsqlCommand c,string search,string? status,bool archived,int page,int size){c.Parameters.AddWithValue("archived_only",archived);c.Parameters.AddWithValue("status",status??string.Empty);c.Parameters.AddWithValue("search",string.IsNullOrWhiteSpace(search)?string.Empty:$"%{search}%");c.Parameters.AddWithValue("limit",size);c.Parameters.AddWithValue("offset",(page-1)*size);}
    private static async Task AuditAsync(NpgsqlConnection c,NpgsqlTransaction? t,Guid id,string action,string entity,string description,string status,decimal amount,CurrentUser actor,CancellationToken token){await using var x=c.CreateCommand();x.Transaction=t;x.CommandText="insert into public.audit_records(record_id,module,action,entity,description,actor_id,actor_name,tone,amount,status) values(@id,'Quotations',@action,@entity,@description,@actor,@name,@tone,@amount,@status)";x.Parameters.AddWithValue("id",id);x.Parameters.AddWithValue("action",action);x.Parameters.AddWithValue("entity",entity);x.Parameters.AddWithValue("description",description);x.Parameters.AddWithValue("actor",actor.Id);x.Parameters.AddWithValue("name",actor.Username);x.Parameters.AddWithValue("tone",action is "Created"?"success":action is "Voided"?"danger":"info");x.Parameters.AddWithValue("amount",amount);x.Parameters.AddWithValue("status",status);await x.ExecuteNonQueryAsync(token);}
    private async Task<T> ExecuteAsync<T>(Func<NpgsqlConnection,NpgsqlTransaction?,Task<T>> action,CancellationToken token){await using var c=await dataSource.OpenConnectionAsync(token);await using var t=Transaction.Current is null?await c.BeginTransactionAsync(token):null;var result=await action(c,t);if(t is not null)await t.CommitAsync(token);return result;}
    private static bool IsSubmit(SaveQuotationRequest r)=>string.Equals(r.Intent,"submit",StringComparison.OrdinalIgnoreCase);
    private static void ValidateTransition(string current,string target,string? reason){var valid=current switch{"Draft"=>target is "For Approval" or "Voided","For Approval"=>target is "Draft" or "Approved" or "Rejected" or "Voided","Rejected"=>target is "Draft" or "For Approval" or "Voided","Approved"=>target is "Voided",_=>false};if(!valid)throw new ResourceConflictException($"Quotation status cannot change from {current} to {target}.");if(target is "Rejected" or "Voided"&&string.IsNullOrWhiteSpace(reason))throw new RequestValidationException("A reason is required.");}
    private static ConcurrencyConflictException Stale()=>new("This quotation changed after you opened it. Reload and try again.");
    private sealed record Header(Guid Id,string Number,DateOnly Date,Guid? ClientId,string ClientName,Guid? ContactId,string ContactPerson,string Subject,string Location,string LeadTime,string Notes,string Terms,decimal Subtotal,bool VatEnabled,decimal VatRate,decimal Vat,decimal Total,decimal Profit,string Status,string? RejectionReason,string? VoidReason,DateTimeOffset CreatedAt,DateTimeOffset UpdatedAt,DateTimeOffset? ArchivedAt,long Version);
    private sealed record ClientSnapshot(Guid? Id,string Name,Guid? ContactId,string ContactName);
    private sealed record ResolvedLine(Guid Id,Guid? ItemId,Guid? VariantId,string? Photo,string Name,string Variant,string Code,string Unit,decimal Quantity,decimal UnitPrice,decimal UnitCost);
    private sealed record Totals(decimal Subtotal,decimal Vat,decimal Total,decimal Profit);
}
